### ISSUE TITLE
order of registering plugins

### ISSUE THREAD

**Issue by flexphperia** [GetSimpleCMS/GetSimpleCMS#1001]
There is no way to control order that plugins being registred in a ```plugin_functions.php``` file in 
```foreach ($live_plugins as $file=>$en) ``` loop.
I'm not completly sure but on some shared hosting order of plugins was different that the order on other hosting.

Order of plugins is the same as in plugins.xml file that is created using ```getFiles``` function that returns an array of files from the passed path.

Can someone confirm that order of files are always the same on any server when using code from that function?

**Comment by tablatronix** [comment]
order is random, and should never be used for synchronous actions.

3.4 has hook priorities, that let you set priority on add_action.
#977

**Comment by flexphperia** [comment]
Sometimes there is no way to not rely on plugin registration order, it should be always alphabetical order or something.
I'm not talking about ```add_action```.

**Comment by tablatronix** [comment]
Why should it be alphabetic? and why do you need to rely on it ?

**Comment by flexphperia** [comment]
It would be nice to have it sorted in any way. Any order but the same
across different servers.
Im using it in Special Pages Extras plugin to replace main admin function
of Special Pages plugin. This is the only way to detect when special pages
configuration is saved.

**Comment by tablatronix** [comment]
specifics? how does order help you override?

**Comment by flexphperia** [comment]
My override must be called after special pages plugin. If not it will not
work.
I not have right now server that fails it but had one in past where order
of plugin register was different.

**Comment by tablatronix** [comment]
i understand, I meant specifically what are you doing , and how are you doing it, that the order matters?

**Comment by flexphperia** [comment]
Something like this
```$plugin_info['i18n_specialpages']['load_data'] = 'spe_i18n_specialpages_main';```

**Comment by tablatronix** [comment]
ok thanks, that is what I figured.

**Comment by tablatronix** [comment]
Let me know if that will work for your specific issue or not.

**Comment by flexphperia** [comment]
It will not.work for me. Take a loook into source code of Special.Pages and
Special Pages Extras plugin to see.
I only need to replace main functiob.

**Comment by tablatronix** [comment]
right soooo


```php
// hooked common
// more than one way to skin a cat
if(get_filename_id() == 'load' && $_GET['id'] == 'i18n_specialpages'){
  global $plugin_info;  
  $plugin_info['i18n_specialpages']['load_data'] = 'spe_i18n_specialpages_main';
}
```

**Comment by tablatronix** [comment]
granted this is probably not the ideal way modifying plugin globas, but its a hack to begin with so who cares.

**Comment by tablatronix** [comment]
I am not going to fix this, seems like a hack, and we don't want people relying on plugin loading order for critical functionality nor want it as a feature.

however, I am adding hack support to force some plugins to load first and in order specified.
This is a user hack so users can do this themselves.

```
// (str) csv list of plugin ids to load first and in order, kludge and not supported
define('GSPLUGINORDER','sa_development.php,sa_hook_components.php');
```
