### ISSUE TITLE
invalid characters in passwords

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1011]
http://get-simple.info/forums/showthread.php?tid=7090&pid=49708#pid49708

% character

**unconfirmed**

**Comment by cnb** [comment]
I have no issues with password `g*RpkZ6nm%B4`
Tested locally (xampp) and in a GS site (cpanel hosting)

**Comment by hameau** [comment]
Not a problem for me in GS 3.3.5, with the following plugins active:
* I18N Special Pages extras
* DynPages
* I18N Base
* I18N
* I18N Search
* I18N Special Pages
* Image Resize Filter
* Multi User

Using commercial shared hosting (ovh.com).

**Comment by tablatronix** [comment]
no reports, closing
