### ISSUE TITLE
JS in the header

### ISSUE THREAD

**Issue by ReneMuetti** [GetSimpleCMS/GetSimpleCMS#1021]
I noticed that are integrated in the backend has a "strange" way the javascripts. Here again, the setting
```
define ("GSNOCDN", false);
```
completely ignored.
is that so wanted?
example:
http://info-panel.net/GetSimple-wrong_path.png

**Comment by tablatronix** [comment]
You get fallbacks even with nocdn? What exactly is the problem here?

**Comment by tablatronix** [comment]
you mean //domain ?
protocol asset urls
#623
