### ISSUE TITLE
Error when dissabling plugin, plugin not dissabled

### ISSUE THREAD

**Issue by datiswous** [GetSimpleCMS/GetSimpleCMS#1024]
GS Version 3.4.0a

When I try to disable a plugin I get an error and the plugin is not disabled.

In data/other/logs/errorlog.txt I see the following error:

`PHP Warning:  Invalid argument supplied for foreach() in *mysiteroot*/admin/inc/caching_functions.php on line 382`

**Comment by tablatronix** [comment]
#1019

**Comment by tablatronix** [comment]
You shouldn't get this error when disabling plugins, but it should be fixed now.
