### ISSUE TITLE
Page 'Meta Description' contains Style/Script declarations

### ISSUE THREAD

**Issue by johnstray** [GetSimpleCMS/GetSimpleCMS#1050]
If a page has no 'Meta Description' set and `GSAUTOMETAD` is true, then any page which contains inline `<style></style>` tags will pollute the 'Meta Description' with CSS declarations. The same situation applies with `<script></script>` tags.

This occurs because `strip_tags()` is called on the description which removes the tags, but not the declarations therein. A solution might be to remove the contents of the tags before calling `strip_tags`.

This could be archeived by using `preg_replace` or `preg_match`, but this is not the most reliable solution. So, I suggest the following changes to the code; it uses the DOMDocument class to handle the removal of the script and style tags before it has strip tags applied to it:

**Before:**
```php
	// meta description from v3.3.5
	if ($metad != '') {
		$description = get_page_meta_desc(FALSE);
	} 
	else if(getDef('GSAUTOMETAD',true))
	{
		// get meta from content excerpt
		if (function_exists('mb_substr')) { 
			$description = trim(mb_substr(strip_tags(strip_decode($content)), 0, 160));
		} else {
			$description = trim(substr(strip_tags(strip_decode($content)), 0, 160));
		}

		$description = str_replace('"','', $description);
		$description = str_replace("'",'', $description);
		$description = preg_replace('/\n/', " ", $description);
		$description = preg_replace('/\r/', " ", $description);
		$description = preg_replace('/\t/', " ", $description);
		$description = preg_replace('/ +/', " ", $description);
	}

	if(!empty($description)) echo '<meta name="description" content="'.$description.'" />'."\n";
```
**After**
```php
  // New Meta Description
  if (!empty($metad)) 
  {
    $description = get_page_meta_desc(false);
  }
  elseif (getDef('GSAUTOMETAD',true)) 
  {
    # Generate Meta Description from content excerpt
    # Updated to handle 'script' & 'style' tags by also removing their content.
    # @uses: DOMDocument | @modifies: $description
    # Written 2015-06-03 04:00am by GitHub: johnstray
    $dom = new DOMDocument('1.0','UTF-8');
    $dom->loadHTML($description);
    $scripts = $dom->getElementsByTagName('script');
    $styles = $dom->getElementsByTagName('style');
    while ( ($node = $scripts->item(0)) || ($node = $styles->item(0)) ) {
        $node->parentNode->removeChild($node);
    }

    // Replace multipe preg_replace() with single containing '\s' (white-space)
    // The covers all the previous \n, \r & \t replacements
    $description = preg_replace('/\s+/', ' ', trim(strip_tags($dom->saveHTML())));
    $description = str_replace('"','', str_replace("'",'', $description));
  }
  if(!empty($description)) echo '<meta name="description" content="'.$description.'" />'."\n";
```

**Comment by cnb** [comment]
Ah yes, I always forget to report this issue.

An alternative to strip_tags that I intented to suggest:
http://nadeausoftware.com/articles/2007/09/php_tip_how_strip_html_tags_web_page
(Don't know if John's solution is better)

**Comment by johnstray** [comment]
My solution uses the DOMDocument PHP class to look for any Script / Style tags in the content, then removes them and any child content under them. I choose this method as it's much more reliable than using `preg_match()` or `pre_replace()` which will easily break if (for whatever reason) the Script / Style tags contain nested tags. I did a bit of research into the topic first.

**Comment by tablatronix** [comment]
style tags are not allowed in body...

**Comment by johnstray** [comment]
Not in the HTML4.1 or less standard, no, however they are quite commonly used and supported by most major browsers. HTML5, on the other hand, has support for "scoped" stylesheets, something I found whilst searching for CSS tips, however, browser support for this is currently limited.

https://css-tricks.com/saving-the-day-with-scoped-css/
http://www.w3schools.com/tags/att_style_scoped.asp

**Comment by tablatronix** [comment]
I suppose this should be using excerpt functions...
Ill implement it using native functions.

**Comment by johnstray** [comment]
Native functions?

**Comment by tablatronix** [comment]
natrive gs funcitons

**Comment by tablatronix** [comment]
added optional elem stripping to `cleanhtml` using dom
added generic function for whitespace stripping for newlines and tabs, non regex
using excerpt functions for generating metad from content.

content might not be filtered, uses global, always has i think.
also adds ellipsis, i might have to remove that if undesired...

**Comment by johnstray** [comment]
Should probably be set for `<script>` elements too. So:

`$desc = cleanHtml($desc,array('style', 'script')); // remove style/script elements`

**Comment by tablatronix** [comment]
Some docs say single quotes are ok in meta desc...

**Comment by cnb** [comment]
If desc is enclosed in double quotes, there should be no trouble with single quotes inside.

But just in case someone uses single quotes (`description='this is the description'`), or uses this for other stuff, I would just convert both single and double quotes to their html entities.

**Comment by tablatronix** [comment]
True, not sure why we always removed them, i think in the past entities in metas were treated suspiciously by bots.

**Comment by tablatronix** [comment]
```
<a href="http://get-simple.info">GetSimple CMS</a><br />
<p>Система управления контентом</p>
<p>These are "quotes" and 'single' and some other stuff &gt; &lt; &amp;</p>
<style type="text/css">h1{
font-weight:bold;
}
</style>
```

`<meta name="description" content="GetSimple CMS Система управления контентом These are &quot;quotes&quot; and &#039;single&#039; and some other stuff &amp;gt; &amp;lt; &amp;amp; Thank you for using GetSimple CMS. This is..." />
`

**Comment by cnb** [comment]
Great.

(rel: a discussion we had ages ago https://github.com/GetSimpleCMS/GetSimpleCMS/issues/59#issuecomment-10025397 )

**Comment by tablatronix** [comment]
double encoded entities...
ugh

**Comment by cnb** [comment]
Related to this, it would also be nice if defacto standard placeholders like {% ... %} (DynPages) and (% ... %) (many plugins) were also stripped out.

I18N Base, Search, and News Manager do it like this (for excerpts):
```php
$content = preg_replace('/\(%.*?%\)/', '', $content);
$content = preg_replace('/\{%.*?%\}/', '', $content);
```

**Comment by tablatronix** [comment]
ok we have a function for this, i didnt know htmlspecialchars had a double encode arg.
`encode_quotes()`
changed code again, for the last time I hope

Ideally with a metad filter these can be removed or replaced, right now there is not a process.

I can run content through a filter first, but that might be a bit wasteful

**Comment by tablatronix** [comment]
#1051
