### ISSUE TITLE
strip shortcodes

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1051]
`define('GSCONTENTSTRIP',true); // default pattern is '/[({]%.*?%[})]/'`
`define('GSCONTENTSTRIPPATTERN', '/[({]%.*?%[})]/'); // custom pattern`

Allows stripping of shortcode or an arbitrary pattern. Always runs after content filters are processed

**Comment by tablatronix** [comment]
Where else would we want to do this ?

**Comment by tablatronix** [comment]
@cnb you want to review this and test it ?

**Comment by cnb** [comment]
Seems to work fine. Tested with Dynpages 
{% ... %} is removed from the meta desc as expected.

**Comment by cnb** [comment]
Excerpts are not run through the content filter as of 3.3.5 (and current 3.3.6 beta). You mean for 3.4?

**Comment by tablatronix** [comment]
get_page_excerpt executes content filter

**Comment by cnb** [comment]
Ah yes. I thought it was called by get_header for the meta desc.

**Comment by tablatronix** [comment]
yeah i would have had to add a return_ function to use that, so i just used getexcerpt basic, plus i figured running 2 content filters per page request would be undesired. Not something i want to solve for in a hotfix.

**Comment by cnb** [comment]
line 51
```php
	$content_e = exec_filter('content',$content_e);
	if(getDef('GSCONTENTSTRIP',true)) $content_e = strip_content($content_e);	
```
Shouldn't the filter be run after stripping the codes?

**Comment by tablatronix** [comment]
then the filter would not work... dynpages wouldn't work if there was no codes

**Comment by cnb** [comment]
I see. I thought the gsconfig setting would enable removing all shortcode contents, like in I18N Search (and currently NM)

**Comment by tablatronix** [comment]
It only removes it if its not processed

**Comment by tablatronix** [comment]
hmm, i see what you mean, but not sure i understand why you would want to.
I guess if you wanted to prevent these plugins from working, there are others ways to accomplish it.

**Comment by cnb** [comment]
I suppose that depending on what you use shortcodes for, one solution would be more adequate than the other....
