### ISSUE TITLE
/data/uploads/.htaccess - error 500

### ISSUE THREAD

**Issue by danielrocher** [GetSimpleCMS/GetSimpleCMS#1052]
Hi,

I test getSimple CMS 3.3.b3  and I get an error 500 when I want to open a file on /data/uploads/.

When I remove this line :
php_flag engine off
in .htaccess, there is no error. What happen ?

PHP - Version	5.4.39 - OK
cURL Module	Installé - OK
GD Library	Installé - OK
ZipArchive	Installé - OK
SimpleXML Module	Installé - OK
chmod	chmod - OK
Apache Web Server	Apache - OK
Apache Mod Rewrite	Installé - OK

Thanks

**Comment by tablatronix** [comment]
What kind of file are you opening ?

**Comment by danielrocher** [comment]
pdf or jpg. 
I just tested with PHP 5.6, and I have same error. Perhaps this comes about my host. But I have no problems with getsimpleCMS 3.3.4.

**Comment by tablatronix** [comment]
yeah, It is apache related..

**Comment by tablatronix** [comment]
I guess we cannot use 'php_flag engine off' if it is not compatible with some hosts.

**Comment by danielrocher** [comment]
others tests: 'php_flag engine off' works for one.com but not for 1&1.

thank you very much for your excellent work

**Comment by tablatronix** [comment]
Looks like it requires
`AllowOverride Options FileInfo AuthConfig` which might be locked down on paranoid hosts.
Not a bad idea for upload directories where someone might be able to upload a htaccess to override system settings.

**Comment by danielrocher** [comment]
Hi,

With this lines :
```
<IfModule mod_php5.c>
  php_flag engine off
</IfModule>
```

There is no error, but I don't know if this is a good method ...
