### ISSUE TITLE
Stored XSS in the USER profile

### ISSUE THREAD

**Issue by a0xnirudh** [GetSimpleCMS/GetSimpleCMS#1074]
All the users has the ability to update their own user profiles which mainly **Username**, **Email Address** and **Display Name**. The Display Name option is vulnerable to stored XSS.

Payload = admin"onmouseover="alert(1)";

![screenshot](https://cloud.githubusercontent.com/assets/5573458/8636800/13b5dfec-2892-11e5-9a92-a6a2de647eb5.png)

Save it and go to some other pages and come back to profile. Hovering the mouse over the display name will trigger the XSS.

**Comment by cnb** [comment]
quick fix: `echo htmlspecialchars(...)` in *settings.php* line 249 (hotfixes):
```php
<input class="text" id="name" name="name" type="text" value="<?php if(isset($NAME1)) { echo htmlspecialchars($NAME1); } else { echo htmlspecialchars($NAME); } ?>" /></p>
```

**Comment by tablatronix** [comment]
This problem goes away if i convert all these fields to cdata, I am not entirely sure why though.

it encodes the same..

```
<NAME>xss &quot;onmouseover=alert(1);&quot;</NAME>
<NAME><![CDATA[xss &quot;onmouseover=alert(1);&quot;]]></NAME>
```

**Comment by tablatronix** [comment]
it seems that LIBXML_NOCDATA performs a entitiesencode of a sorts.
My guess would be `filter_var` `FILTER_SANITIZE_SPECIAL_CHARS` because it uses `&#34;` instead of `&quot;&`

**Comment by tablatronix** [comment]
I think this explains finally why we really have `strip_decode` on everyting, to handle encoded entities in cdata, although they do not have to exist they probably do due, to sanitization and old text nodes.

**Comment by tablatronix** [comment]
#618

**Comment by tablatronix** [comment]
same goes for permalink structure
