### ISSUE TITLE
Problem with index sub pages

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1079]
1. Create sub page for index page.
2. Turn on FancyURLs with %parent%/%slug%/ pattern.

Now created sub page has an address http://site-url/index/sub-page/

Navigate to it and you will get index page, not sub page.

**Comment by tablatronix** [comment]
works for me

**Comment by dimayakovlev** [comment]
I have tried on hosting server and it works fine too. But on my localhost (Windows and XAMPP) doesn't work.

Maybe it is a false warning.

**Comment by tablatronix** [comment]
are you sure fancyurls are even working ?

**Comment by dimayakovlev** [comment]
Yes, other pages works fine. Only index sub pages have problems.

**Comment by tablatronix** [comment]
version ? 3.3.6 ?

**Comment by dimayakovlev** [comment]
Yes, 3.3.6.

Local server: Apache 2.2.21 (Win32), PHP 5.3.8.

**Comment by tablatronix** [comment]
Clean install , no plugins, no other html or index files in your directory that do not belong ?

and other fancyurls work ?
/index2 for example

**Comment by dimayakovlev** [comment]
Clean install, no plugins, no additional configuration via htacess.

Subpage for Test page works fine.
![Subpage for Test page](https://cloud.githubusercontent.com/assets/8279974/8895766/07f5188c-33ee-11e5-9b27-9613b8c30350.png)

Subpage for Index page... It is Index page.
![Subpage for Index page](https://cloud.githubusercontent.com/assets/8279974/8895792/c70bad58-33ee-11e5-9678-c78c2188f95c.png)

**Comment by dimayakovlev** [comment]
I have created "index" dir in root directory and problem has gone.

**Comment by tablatronix** [comment]
I wonder if you are experiencing the opposite of this bug
#940 , this bug prevents actual files from loading, your seems to be preventing index/page from loading perhaps because apache thinks there is a folder called 'index' and is looking inside it ?

This line
`RewriteCond %{REQUEST_FILENAME} !-f`
prevents the fancy url rewriting if an actual file exists.

But I can't imagine how this would cause a false positive for 
index/page/

Do you have a folder named `index` anywhere else in your webroot ?

it still makes no sense.

there are 3 things you can try.

- [ ] comment out the 2 lines before the rewrite rule, and see if the problem goes away
- [ ] enable rewrite logging and see if it says what is going on

**Comment by tablatronix** [comment]
Also are you using the default permalink ? or are you entering it yourself ?

**Comment by dimayakovlev** [comment]
Permalink has default value.

Index folder was created special for test, there are no other created folders.

Result with commented RewriteCond strings:
![Index subpage works](https://cloud.githubusercontent.com/assets/8279974/8910094/8c4996ea-348d-11e5-9ae5-f130ae40b080.png)
Index subpage work, but index page does not:
*http://192.168.1.100:8087/ - page not found;
*http://192.168.1.100:8087/index/ - page not found.

I was not able to get data in rewrite.log. Log was successfully created, but it is empty. And there are no errors in error log. Maybe it is problem in XAMPP.

Alternative rules did not helped.

**Comment by n00dles** [comment]
https://github.com/GetSimpleCMS/GetSimpleCMS/issues/713

**Comment by dimayakovlev** [comment]
n00dles, I have described opposite problem - if no index folder, no subpages for index page.

**Comment by n00dles** [comment]
ah, sorry I thought you said you had an index folder for testing.

**Comment by dimayakovlev** [comment]
It was the answer to Shawn about "index" folders.

Issue can be closed. I have installed standalone Apache server and have configured it. Now everything works as expected.

**Comment by tablatronix** [comment]
very odd issue indeed, must be a configuration rule for default page or something being odd.
There are some wierd issues like this in apache 2.2. but this is a first, maybe your server tries to add .php by default to index/ then it fails the rewritecond check..

shrug

**Comment by tablatronix** [comment]
Even though we cannot reproduce this, I am leaving it open in case it pops up again, or if I encounter anything similar.

**Comment by tablatronix** [comment]
closing stale no reports
