### ISSUE TITLE
getParent and getParentMulti functions

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1084]
There are getChildren and  getChildrenMulti functions in caching_functions.php. I think GetSimple needs getParent and getParentMulti functions too.

**Comment by tablatronix** [comment]
Much more than this is available in 3.4 already

**Comment by tablatronix** [comment]
I will take suggested function names though and any other shortcut functions and front end facing functions that might be wanted.
