### ISSUE TITLE
write XML line by line

### ISSUE THREAD

**Issue by almendro** [GetSimpleCMS/GetSimpleCMS#1090]
(english is not my mother language so, please, forget me for my poor spelling)

I use GIT for versioning my sites and the problem are the XMLs in one big line, so I decide break it tag by tag.

In admin/inc/caching_functions.php, at the end of file after saving the data insert lines chars between >< (I will push in my fork very soon)

Open originaly in forum
http://get-simple.info/forums/showthread.php?tid=7474

**Comment by tablatronix** [comment]
#1089
