### ISSUE TITLE
Core mechanisms for plugins shortcodes

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1093]
GetSimple has no built in mechanism that supports plugins shortcodes. I think that it must have feature, that will makes plugin development easier.

Shawn, can you share your thoughts about best way to implement shortcodes in plugins?

**Comment by tablatronix** [comment]
I have an idea but did not plan on implementing yet.

**Comment by tablatronix** [comment]
#557

**Comment by dimayakovlev** [comment]
@tablatronix Ok! But what is the better way to handle shortcodes? Can you post example of  efficient way to parse shortcode and get parameters from it?

For example: (% MyShortcode param1:value param2:"Long text value" %).

**Comment by tablatronix** [comment]
It is an elaborate regular expression I have written one , dynpages uses one, I think i18n plugins also have a pretty good one.
