### ISSUE TITLE
Native frontend cahing support

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1094]
There is Simple Cache plugin for frontend caching: http://get-simple.info/extend/plugin/simplecache/56/ It using "index-pretemplate" action for loading cache file.

I my opinion cached page can be loaded earlier in index.php and without checking caching settings - if cache file exists, when use it.

**Comment by tablatronix** [comment]
Sooo what are you asking formor reporting?

**Comment by dimayakovlev** [comment]
It's just an idea.

**Comment by tablatronix** [comment]
What is it an idea for? 
That is a plugin, it has nothing to do with GS core, unless you are asking for a new hook I do not see how this is an issue or feature request.

**Comment by dimayakovlev** [comment]
This plugin is just example how caching is implementing now via plugin. But caching is an important feature and better if it will be part of the GetSimple core. That's what I meant. :)

**Comment by tablatronix** [comment]
core plugin maybe but there is too much user specific requirements even for individual pages,

**Comment by tablatronix** [comment]
deferring to plugin development
