### ISSUE TITLE
exec_action in image.php

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1100]
Shawn, can you add new exec_action into image.php after line 83? For example, this action can be used to show form for image (title, description) via plugin.

**Comment by tablatronix** [comment]
before or after thumbnail cropper? I am thinking before, try this out.

**Comment by tablatronix** [comment]
An image meta plugin would be sweet, I would like al files to open in a media page one day also

**Comment by dimayakovlev** [comment]
Nice! I create plugin special for test: https://github.com/dimayakovlev/getsimple-plugin-imagefields
Please add this hook into GetSimple 3.3.* too.

**Comment by tablatronix** [comment]
no enhancements on minor versions, this includes hooks

**Comment by tablatronix** [comment]
#719
