### ISSUE TITLE
Reflected XSS - Uploads section

### ISSUE THREAD

**Issue by joelvadodil** [GetSimpleCMS/GetSimpleCMS#1103]
Hi team,

There is a reflected XSS issue in the "uploads" section in version 3.3.7. When we pass the payload in the folder name section the payload gets executed and the folder gets created.

Payload - `><img src=x onerror=alert(document.cookie); >.jpg`

Please check and close this issue.

Reference:

![reflected xss-uploads](https://cloud.githubusercontent.com/assets/12528123/10425721/8ced2bb6-70e2-11e5-9d32-5d4b60348310.jpg)

**Comment by tablatronix** [comment]
wow, i had no idea jquery selectors were injectable. wtf ( at least this is fixed in newer versions )

newfolder is evaluated here!
`$("tr." + newfolder + " td").css("background-color", "#F9F8B6");`
