### ISSUE TITLE
components slug spaces

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1114]
component and snippet slugs are wrong with regards to spaces.

`some spaces up in here`
`<?php get_component('some spaces up in here'); ?>`

**Comment by tablatronix** [comment]
This is only when adding components or changing titles, hence a js problem.

**Comment by Every0ne** [comment]
Was this touched? Cuz' I'm running into a problem where spaces in component' names are saved as dashes in xml, but in admin panel they are shown as underscores.

**Comment by tablatronix** [comment]
Hmm
