### ISSUE TITLE
Core Data Files can not be used as custom data storage

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1120]
It's not issue, but website.xml losing all custom data when changing website theme (lines 30 - 39 in theme.php). So, It can not be used to store data from plugins.

But in my opinion website.xml is nice place to store global data.

**Comment by tablatronix** [comment]
yeah I think i fixed a similar issue, or maybe the same one in 3.4
I will check

**Comment by tablatronix** [comment]
I think is still an issue with 
- [ ] settings
- [ ] theme
- [ ] user profiles

**Comment by tablatronix** [comment]
Will probably fix in 3.4 but not in 3.3.x.
storing custom fields in core datafiles is not supported in 3.3 no use fixing it now.
plus we already have supporting functions in 3.4 to do it much easier.

**Comment by tablatronix** [comment]
actually bumped to 3.5, 3.4 is closed to features.

**Comment by dimayakovlev** [comment]
Maybe to add new data file special for storing custom data? And some basic methods for working with it.

**Comment by tablatronix** [comment]
That is a road map goal

**Comment by dimayakovlev** [comment]
Shawn, can you fix overwriting of all data stored in website.xml during saving chosen theme? In 3.3.9 release. Now plugins can add their data to website.xml with settings-website-extras hook, but code in theme.php destroys all of added data.
This code doesn't add new features, just fix issue, so it can be added to 3.3.9 version.
```
  $xml = getXML(GSDATAOTHERPATH . $file);
  if ($xml) {
    $xml->TEMPLATE = $TEMPLATE;
  } else {
    $xml = new SimpleXMLExtended('<item></item>');
    $note = $xml->addChild('SITENAME');
    $note->addCData($SITENAME);
    $note = $xml->addChild('SITEURL');
    $note->addCData($SITEURL);
    $note = $xml->addChild('TEMPLATE');
    $note->addCData($TEMPLATE);
    $xml->addChild('PRETTYURLS', $PRETTYURLS);
    $xml->addChild('PERMALINK', $PERMALINK);
    XMLsave($xml, $path . $file);
  }
  XMLsave($xml, $path . $file);
```

**Comment by tablatronix** [comment]
I suppose, i can probably skip all that no xml nonsense also since that would be a fatal condition.

**Comment by tablatronix** [comment]
I fixed up theme.php for now, so you can handle stuff in settings, but settings will still overwrite by itself, but its fairly easy to workaround that.

**Comment by dimayakovlev** [comment]
Can you fix up theme.php for 3.4 too?

**Comment by tablatronix** [comment]
Hotfixes has to be merged into master and conflicts resolved so i have not had a chance to do that yet.
