### ISSUE TITLE
Open graph meta tags

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1123]
It's nice to have Open Graph meta tags support in theme functions.

**Comment by tablatronix** [comment]
Yes it would
left for plugins, 3.4 has a meta tab just for this stuff to go

SEO plans for future versions
#598

**Comment by dimayakovlev** [comment]
Off topic, but I really like tabs in 3.4. :)
I written plugin for  primary Open Graph and Twitter Card meta tags support but for 3.3 and without i18n.
It has global settings with token replacements for og:title and og:description, and per page settings.
![untitled](https://cloud.githubusercontent.com/assets/8279974/11425716/e86fb906-9467-11e5-9159-afdb829dd249.png)

**Comment by tablatronix** [comment]
neato

**Comment by dimayakovlev** [comment]
Plugin for GS 3.4: https://github.com/dimayakovlev/getsimple-plugin-socialization
