### ISSUE TITLE
Add timestamp for new files

### ISSUE THREAD

**Issue by BulatSa** [GetSimpleCMS/GetSimpleCMS#1125]
Add please timestamp for new files after load on server. Because now all files can storage on browser cache and don't update for all clients.
Example what i mean: 
src='files/book.pdf' --> src='files/book.pdf?v=202155412'

**Comment by tablatronix** [comment]
This is controllable by your host cache control.
Add proper cache headers to your httpd, or .htaccess for those files.

or
see if there is a ckeditor plugin to nocache inline assets
