### ISSUE TITLE
GetSimple CMS 3.3.7-Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by tigerboy07** [GetSimpleCMS/GetSimpleCMS#1129]
[GetSimple_CMS_XSS.txt](https://github.com/GetSimpleCMS/GetSimpleCMS/files/72058/GetSimple_CMS_XSS.txt)

**Comment by tablatronix** [comment]
Allows image injection, but we allow html in titles for legacy. Will be removed or allow filtering in future.

**Comment by tigerboy07** [comment]
template parameter is also vulnerable.

On Sat, Jan 2, 2016 at 8:12 PM, Shawn A <notifications@github.com> wrote:

> Allows image injection, but we allow html in titles for legacy. Will be
> removed or allow filtering in future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GetSimpleCMS/GetSimpleCMS/issues/1129#issuecomment-168396609>
> .
>



-- 
Best Regards,

*Sachin Wagh*
Security Consultant
m: +91 75 888 644 81
w:  secur1tyadvisory.wordpress.com

**Comment by tablatronix** [comment]
#1127

**Comment by tablatronix** [comment]
I believe this was fixed by another fix

**Comment by tablatronix** [comment]
#1293
