### ISSUE TITLE
Make fancy urls and custom permalink easier to understand and use

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1133]
The way it is now its very confusing.

If you enter a custom permalink pattern , then toggling the fancy url setting does nothing.
This is very confusing.

You also cannot toggle the custom rule on and off.

So a way to combine these settings and make them easier to use would be nice.

**Comment by tablatronix** [comment]
Maybe we should just get rid of the fancy urls checkbox, and use it as a permalink enable checkbox. But that is not backward compatible, but we could check it if a permalink is set on upgrade.

**Comment by tablatronix** [comment]
This might cause some confusion with how to toggle between index.php and fancy, but index.php?id always works so it probably makes no difference. Im gonna change it and see what people think.

**Comment by tablatronix** [comment]
ok i have made the changed and i think it clarifies the settings, all references to prettyurls/fancyurls will be eventually removed and just use custom url. all these names are the same thing and confusing.

leaving variable names the same for now for legacy support.

I also added a toggle to disable custom url structure to make it even clearer.
I will have to add an upgrade path to enable prettyurls on if permalink is no empty.

- [ ] upgrade.php load website.xml if permalink not empty, enable prettyurls save xml

**Comment by tablatronix** [comment]
prettyurls is now 
` Enable Custom URL`
and it must be enabled in 3.4 for fancy urls to work

upgrade script will auto enable it if a fancy url exists, and will add a GSVERSION field to settings.

This might be considered a breaking change, but I consider it to always have been wrong and confusing.

**Comment by cnb** [comment]
on update.php, 
```
if($fileversion!='3.4.0'){
...
```
wouldn't it be better to check if < '3.4', and save `GSVERSION` instead of `'3.4.0'` ?

**Comment by cnb** [comment]
Maybe it would be better to add a new string for "Enable custom URLs..." instead of reusing `USE_FANCY_URLS `(was: "Use fancy URLs..."). It's a different meaning, and anyway there's another new string related to this that needs to be translated (`URL_SETTINGS`)

**Comment by tablatronix** [comment]
Good point

**Comment by tablatronix** [comment]
But the meaning is still pretty close

**Comment by tablatronix** [comment]
The version is file version not gs version

**Comment by cnb** [comment]
Do you mean something like Settings format version?

**Comment by tablatronix** [comment]
Yes a spec

**Comment by cnb** [comment]
GSVERSION for field name seems confusing to me.
Perhaps VERSION, VER, or SPEC?
Also why 3.4.0 and not 3.4? Could the spec change in dot versions?

**Comment by cnb** [comment]
Ok.

Yeah I supposed so. I assume that version 3.4.1 would still have GSVERSION 3.4.0 in the file, if no changes.

**Comment by tablatronix** [comment]
yeah there would not be a schema or format change in between major versions I suppose it does not need the minor version.
