### ISSUE TITLE
Link to "change password" on a fresh install does not work

### ISSUE THREAD

**Issue by bald** [GetSimpleCMS/GetSimpleCMS#1139]
After a fresh install of GetSimple (v. 3.3.8) and adding a new user through the setup interface, the user is automatically logged in. Then, a request to change the password is shown. But the target of the link does not exist:
`http://192.168.1.29/"settings.php#profile\"`

The page with the wrong link is `http://192.168.1.29/getsimple/admin/support.php?updated=2`

`192.168.1.29` is my local webserver, GetSimple is installed in `/var/www/html/getsimple/`

**Comment by tablatronix** [comment]
Ill check it out, but thats weird that there are quotes in there..

**Comment by tablatronix** [comment]
Cannot reproduce, this sounds like a similar issue in the forums, but it makes no sense. Where are the quotes coming from ?

```html
	<div class="error"><p>Don't forget to <a href="settings.php#profile">change your password</a> from that random generated one you have now...</p></div>	
```

**Comment by bald** [comment]
> Does you profile link in the top right corner work? The welcome yourname one?

Yes

Maybe I get the error because I'm using the [german language file](http://get-simple.info/extend/language/german-language-file-gs-33/762/)?

**Comment by tablatronix** [comment]
possibly, can you post which one you are using and i can test.

**Comment by tablatronix** [comment]
yup It is language file, they changed all the php quotes to single and failed t remove the escaping for double quotes, you will have to change all the \" to just "

**Comment by bald** [comment]
Thanks a lot. I will fix the language file later and upload it.

**Comment by tablatronix** [comment]
Yeah maybe notify the author , it seems to be quite old though
