### ISSUE TITLE
Duplicate id #sitename on settings

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1143]
Unwanted margin-left appears when GSSTYLEWIDE admin style enabled.
![GUI issue](https://cloud.githubusercontent.com/assets/8279974/13123198/3779b5b0-d5cc-11e5-9eeb-88222ecc1fb5.png)

**Comment by tablatronix** [comment]
What browser? Odd that this would show up now when its not new.

**Comment by dimayakovlev** [comment]
I tried Internet Explorer, Firefox and Chrome.
This issue in css-wide.php:
```
.wrapper .nav li:first-child, #sitename {
	/* breathing space for tabs */
	margin-left: 35px;
}
```
#sitename doesn't need margin-left.

**Comment by tablatronix** [comment]
Sitename is the banner in header

**Comment by dimayakovlev** [comment]
Well... Input has id="sitename" too.

**Comment by tablatronix** [comment]
Indeed it does, crap
