### ISSUE TITLE
Processing content before template include

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1150]
IMHO, content must be processed before including template (мaybe with index-pretemplate hook). This gives more flexibility in the use of shortcodes in page content. Now shortcodes have no access to page header, and they cannot add required stuff into it (CSS, JavaScript, tags).

**Comment by tablatronix** [comment]
care to clarify or give example ?
Not sure i understand if you are talking about content filtering or template headers.

**Comment by dimayakovlev** [comment]
I mean that shortcodes processing after get_header function fired. So shortcodes have no access to page header.

**Comment by dimayakovlev** [comment]
For example, If I use DynPage plugin and create component to use it in content, this component cannot use theme-header hook to add something to head of the page.

**Comment by tablatronix** [comment]
That is what plugins are for, not components. How would you access a hook from a component, its not even possible. Components are inline.

**Comment by lokothodida** [comment]
@dimayakovlev : what sorts of things are being put in the theme header? If it's loading scripts and stylesheets, you can do them there in the component, and either use PHP globals or static variables to echo the content a fixed number of times (e.g. loading a Javascript/CSS file once).

```php
// Component: load-my-js
// Usage: {% load-my-js %}
// Loads path/to/my/script.js only on first call
if (!function_exists('load_my_js')) {
  function load_my_js() {
    static $loaded = false;

    if (!$loaded) {
      echo '<script src="path/to/my/script.js"></script>';
      $loaded = true;
    }

    // now its loaded, do what you want in the next <script> block
  }
}

load_my_js();
```

If it is anything that is meant to modify meta-information about the page (e.g. page title), then it's not really the kind of thing that should be in a component. Although you could output Javascript that modifies the `title` HTML tag after the page has loaded.

**Comment by tablatronix** [comment]
I think you are even allowed to put style tags inline if they use `scoped` attribute in html5

**Comment by dimayakovlev** [comment]
@tablatronix, I was wrong. It is possible that an example with the components was not the best. But I was sure that this code should work:
```
<?php
$thisfile = basename(__FILE__, ".php");
register_plugin(
  $thisfile, 'Test Plugin', '1.0', 'Dmitry Yakovlev', '', 'Just Test'
);

add_filter('content', 'pluginTest');

function pluginTestAction() {
  echo 'Text in footer';
}

function pluginTestCallback($matches) {
  if ($matches) {
    add_action('theme-footer', 'pluginTestAction');
    return 'Shortcode found';
  }
}

function pluginTest($content) {
  $pattern = '(\(%\s+test-plugin\s+%\))';
  return preg_replace_callback($pattern, 'pluginTestCallback', $content);
}
```
add_action in pluginTestCallback function doesn't work.

@lokothodida, thank you for your example of code.

**Comment by lokothodida** [comment]
@dimayakovlev: You mentioned the `index-pretemplate` hook in the first comment. Is there a problem with doing everything there?

```php
<?php
$thisfile = basename(__FILE__, ".php");
register_plugin(
  $thisfile, 'Test Plugin', '1.0', 'Dmitry Yakovlev', '', 'Just Test'
);

// Processing is done prior to templates being loaded
add_action('index-pretemplate', 'pluginTest');

function pluginTestAction() {
  echo 'Text in footer';
}

function pluginTestCallback($matches) {
  if ($matches) {
    add_action('theme-footer', 'pluginTestAction');
    return 'Shortcode found';
  }
}

// Now the callback processes the $data_index object
function pluginTest() {
  global $data_index;
  $pattern = '(\(%\s+test-plugin\s+%\))';
  $data_index->content = preg_replace_callback($pattern, 'pluginTestCallback', $data_index->content);
}
```

**Comment by tablatronix** [comment]
It should work its just a filter

**Comment by tablatronix** [comment]
A filter needs to return content or null

**Comment by tablatronix** [comment]
And you can just do a preg match no need for callbacks

**Comment by dimayakovlev** [comment]
@lokothodida. It's not a problem. :) Your example does exactly what I asked for. I just thought that it would be good to do this by default.

**Comment by dimayakovlev** [comment]
@tablatronix Can you test my example? Why `add_action('theme-footer', 'pluginTestAction');` in pluginTestCallback doesn't work?

**Comment by lokothodida** [comment]
@tablatronix: I think the point @dimayakovlev is getting at is that `add_filter` is called after processing the templates, and so the `theme-footer` action call is too late to register any callbacks that will actually be invoked

My take on this: `add_filter` should operate as a simple filter on specific pieces of data (e.g. page content), and not try to affect the state of other page information (header, footer, title, etc...). Filters should effectively be stateless, (almost) "pure" functions. When doing more complicated page behaviour, hooks/actions (such as `index-pre/posttemplate` and `error-404`) seem more appropriate.

**Comment by dimayakovlev** [comment]
@lokothodida Yes, you are right.

**Comment by dimayakovlev** [comment]
@lokothodida, I get notice with your code: `
Notice: Undefined index: file in D:\OpenServer\domains\gs-clean\admin\inc\plugin_functions.php on line 254`.
Problem with `add_action('theme-footer', 'pluginTestAction');` in pluginTestCallback function. What's wrong with it? In my example there is no notice, but it doesn't work.

**Comment by tablatronix** [comment]
Yeah that's my point filters are for filtering only. they are not hooks.

There is no way to know when a filter is gonna run or if someone bypasses it, as it is a component of theme getters, and is only called by get_content typically, ( there are some other instances )

Now you can still use components to do this with my plugin, you don't need to write a plugin.
You can also still use dynpages and not have to handle filters at all.  In fact im fairly sure dynpages has a content parser also to check if your token is found. This code can literally be like 3 lines.

**Comment by tablatronix** [comment]
Im closing this, it is beyond scope of  components.
Continue in forums please
