### ISSUE TITLE
version compare is wrong

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1152]
3.3.10 is not working , comparing as dec 1

**Comment by cnb** [comment]
https://github.com/GetSimpleCMS/GetSimpleCMS/issues/830

**Comment by cnb** [comment]
I think this should be fixed in 3.3.9, or else 3.3.9 users would not be notified.

**Comment by tablatronix** [comment]
This was actually an api issue, it was using comparators, i changed it to use `version_compare`

**Comment by cnb** [comment]
oops, I thought it was in the core like in plugins.
