### ISSUE TITLE
Function undo doesn't check if backup file exist

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1154]
This issue is for 3.3.x.
If backup file not exist, used in undo function (declared in template_functions.php) native PHP function copy, shows warning message. So if plugin developer wants to use built in undo function, he must check firstly if backup file exist.

**Comment by tablatronix** [comment]
Is this a fatal error or a warning?

**Comment by dimayakovlev** [comment]
Warning.

**Comment by tablatronix** [comment]
I probably won't fix for a php warning.

You can try this however, returns true and does nothing if there is nothing to restore.


```php
	if(file_exists($bak_file)){
		copy($bak_file, $undo_file); // copy backup
		copy($tmp_file, $bak_file);  // save original as backup
		unlink($tmp_file); 			 // remove temp shuttle file
	} else return true;	
	
```
