### ISSUE TITLE
Allow protocol-agnostic base url in /admin/settings.php

### ISSUE THREAD

**Issue by tobiassoltermann** [GetSimpleCMS/GetSimpleCMS#1160]
Please allow the following format for the field "Website URL" in the settings page (`/admin/settings.php`):

`"//example.com/folder/file.css"`

Reason:
Most browsers reject loading resources over HTTP when the originating html site has been loaded over HTTPS. Many templates nowadays use this syntax in resources links in order to allow protocol agnostic access (HTTP/HTTPS)

Because of the settings panel disallowing to enter the base URL in this format, get_theme_url therefore returns a specific protocol - and themes get broken when loaded over HTTPS.

I tested it, modifying the settings in the file other/website.xml by hand works.

**Comment by tablatronix** [comment]
3.3.4 made all gs assets schemeless amd added a parameter to get siteurl so themes can do the same there is also a global called asseturl 

#623 

3.4 will allow relative urls entirely.

**Comment by cnb** [comment]
@tobiassoltermann
A tip so that you don't need to edit *settings.xml*
Edit *admin/settings.php*, find and remove this string: `type="url"`

**Comment by tablatronix** [comment]
Oh yeah , the only thing that prevent the saving of relative urls is the browser input filter.

So that has been reported to work well, I have tried it to much success, its possible something could break like a plugin but try it.
