### ISSUE TITLE
No redirect after new page creation

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1163]
Issue appears with Internet Explorer 11 and GetSimple 3.4.
![ieconsole](https://cloud.githubusercontent.com/assets/8279974/15589405/c052ef76-23a3-11e6-9f38-002ca2b8f0df.png)

**Comment by tablatronix** [comment]
my god this thing sucks, no stack trace, no line numbers.

**Comment by tablatronix** [comment]
Looks like ie11 might have a problem with localhost ajax.
I added an error catch for this condition and will debug it later

**Comment by tablatronix** [comment]
Try adding to trusted sites

**Comment by dimayakovlev** [comment]
Adding to trusted sites not helps.

**Comment by tablatronix** [comment]
Are you using 127.0.0.1 on a dev bix?

**Comment by dimayakovlev** [comment]
Yes, my local server is 127.0.0.1. Now I have tried on the hosting and got the same error.

**Comment by tablatronix** [comment]
Are you using https?

**Comment by tablatronix** [comment]
Possible ie11 bug
Related to either redirects of specific types 302 etc.
Or keep alive race condition
http://pubdev.hitech.com/test.post.php

**Comment by tablatronix** [comment]
- [ ] add ajaxerror detection and fall back to force form.submit()

**Comment by tablatronix** [comment]
Do you have this problem with any other ajax saves? Components, theme editor?

**Comment by dimayakovlev** [comment]
No, everything else works well.

**Comment by tablatronix** [comment]
changed header to 300, IE 11 refuses to pass proper xhr status if location header is missing on redirect headers, but 300 does work. Since i want an actual page refresh and not an ajax redirect, ideally i can just replace this with custom json responses, but using standard headers for now, since its easier.
