### ISSUE TITLE
Update $dataw variable in settings.php

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1167]
Global variable $dataw must be updated after saving website settings. It's needed for work with custom fields stored in website.xml.

**Comment by tablatronix** [comment]
Settings saves uses $xmls global ( this is a good instance where a filter should replace a global )

Are you talking about upgrade.php ?
Can you give an actual bug or reproducible issue ?

**Comment by dimayakovlev** [comment]
But $xmls exists only if settings were submitted. So it needs to be checked every time.
I written test plugin which can demonstrate what I mean (value in Test Field will not be updated after submitting):
```php
<?php 

$thisfile = basename(__FILE__, '.php');

register_plugin(
  $thisfile,
  'Test Plugin',
  '1.0',
  'Dmitry Yakovlev',
  'https://github.com/dimayakovlev',
  'Just for test',
  '',
  ''
);

add_action('settings-website-extras', function() {
  global $dataw;
  $value = strip_decode($dataw->testField);
?>
<div class="widesec">
  <p><label for="testField">Test Field:</label><input name="testField" class="text" type="text" value="<?php echo $value; ?>"></p>
</div>
<?php
});

add_action('settings-website', function () {
  global $xmls;
  $xmls->addChild('testField')->addCData(isset($_POST['testField']) ? safe_slash_html($_POST['testField']) : '');
});
```

**Comment by dimayakovlev** [comment]
This also occurs with standart "Website URL" field.

**Comment by tablatronix** [comment]
Is this a bug did it used to work does it break a plugin ir is this a request?
I still dont get it dataw is not an official global to hold data

**Comment by tablatronix** [comment]
Ok so this is probably a known issue, the actual issue is
"Settings are not available to gs until after reload since we do not reread them on from file nor set a global cml object"

Basically gs does not support adding stuff to settings, and it has not been added yet, also there is some decisions on how we need to apply settings after save, I say a refresh since you could change site url and lang and break stuff during runtime.

There is an open issue about modifying website files and adding custom data that I still need to figure out.

I also have not decided if the xml globals are going to stay since they consume memory.

**Comment by tablatronix** [comment]
I think maybe a plugin should check wether it is being submitted, since they might decode to change some stuff in realtime or not. If i just reset dataw, then you dont know, I guess a settings save hook could help you change this logic.

**Comment by tablatronix** [comment]
#1153

**Comment by tablatronix** [comment]
Do you think we should maybe just redirect on success, so everything gets reloaded?

What about errors, I can't update dataw on errors, so you still need to handle submissions wont you ?

**Comment by dimayakovlev** [comment]
I think that redirect is the best solution.

**Comment by dimayakovlev** [comment]
And if website.xml can be used to store custom data, needed new function, like this:
```php
function get_website_field($field, $echo = true) {
	global $dataw;
	$str = strip_decode($data_index->$field);
	return echoReturn($str,$echo);
};
```

**Comment by tablatronix** [comment]
Yes there will be a filter and a abstraction method.

**Comment by tablatronix** [comment]
- [ ] settings xml filter

**Comment by dimayakovlev** [comment]
Can you add filter before `exec_action('settings-website')`?

**Comment by dimayakovlev** [comment]
Shawn, please, add redirect after success submission.

**Comment by tablatronix** [comment]
I have not decided on this yet.
What do you need applied after save on the settings page can you clarify the use case.

**Comment by dimayakovlev** [comment]
I want to use custom fields on settings page and store data in website.xml, so I want to have updated $dataw variable after saving settings. This needs to fill custom input fields after saving data with updated values without additional reading updated website.xml or using POST data.
Also there is problem with translation after submitting:
![2016-09-11](https://cloud.githubusercontent.com/assets/8279974/18420024/017f80b0-787a-11e6-8038-fdf3614fb73c.png)

**Comment by tablatronix** [comment]
What is your language set to?

**Comment by tablatronix** [comment]
You keep saying dataw. I need to know where you are using this info that you need it set globally after a ajax save. I need more information of the actual use case so I can engineer it properly. I seriously doubt the solution will use dataw, so i need all the info.

**Comment by tablatronix** [comment]
Also why can you not just add it to dataw yourself in your post handler? Why is that a problem?

**Comment by dimayakovlev** [comment]
@tablatronix check this test example https://github.com/dimayakovlev/getsimple-plugin-extra-fields

**Comment by tablatronix** [comment]
yeah I understand the example but i do not understand the problem, this seems to only be a problem  on the settings page and only when saving, so if saves are ajax the fields are already prefilled.

So the example does not express what the functionality  you are trying to achieve is, or other scenarios.

There are multiple engineering solutions, if siteurl changes i can detect this before common loads and apply it in real time for example and be able to load the changes on the fly even with ajax.

Ill play with this example and see what the problem is.

**Comment by dimayakovlev** [comment]
Yes, this problem only with settings page. I just want to make plugin development easy, without additional pieces of code.

**Comment by tablatronix** [comment]
ok so settings was never even setup as ajaxsaving, so nevermind.

I will have a redirect for testing

**Comment by tablatronix** [comment]
Can you see if this is satisfactory for now.
2accefe330a602c7671f5f28939fe0a3236ea231

I will look into adding actual extra fields support via a filter and making them available instantly so they can be used in hooks such as sitemap generation and other things that occur after save.

**Comment by dimayakovlev** [comment]
Now everything work fine! I think this issues can be closed.

**Comment by tablatronix** [comment]
I know that plugin is a test but in case you are using that code, it just keeps adding nodes to the settings xml over and over.

**Comment by dimayakovlev** [comment]
Yes, I changed code.
Since https://github.com/GetSimpleCMS/GetSimpleCMS/commit/804ca7d997df11c35f93f03c6ce0112ae0f34488 website.xml can store manually added data, so we really need getter function.

**Comment by dimayakovlev** [comment]
Have you plans to implement in place update for pages?

**Comment by tablatronix** [comment]
What do you mean ?

**Comment by dimayakovlev** [comment]
I see this https://github.com/GetSimpleCMS/GetSimpleCMS/issues/1153. This is exactly what I have meant.

**Comment by dimayakovlev** [comment]
Issue can be closed.
