### ISSUE TITLE
Register and queue embedded styles and scripts

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1168]
It would be nice to have ability to register and queue embedded styles and scripts.

**Comment by tablatronix** [comment]
Please clarify "inline" ?

**Comment by dimayakovlev** [comment]
I was incorrect. I mean embedded.
Something like:
```php
$style_body = <<<BODY
body {
	background: black;
	color: white;
}
BODY;
$style_inline = <<<INLINE
.inline {
	display: inline;
}
INLINE;
register_embedded_style('my-style-body', $style_body);
register_embedded_style('my-style-inline', $style_inline);

queue_embedded_style('my-style-body', GSFRONT);
queue_embedded_style('my-style-inline', GSFRONT);
```
And result is:
```html
<head>
  <style>
    body {
      background: black;
      color: white;
    }
    .inline {
      display: inline;
    }
  </style>
</head>
```

**Comment by tablatronix** [comment]
I went ahead and added this feature because it was fairly easy, but I do have concerns of people just shoving large amounts of data and causing overuse of memory.

**Comment by dimayakovlev** [comment]
I try this code:
```php
register_style_code('test-embedded', 'body { background: black; }', '');
queue_style('test-embedded', GSFRONT);
```
And got just `body { background: black; }` without <style></style> tags.

**Comment by tablatronix** [comment]
yeah there are no tags, see the tasks

**Comment by dimayakovlev** [comment]
`function register_style_code($handle, $src, $ver, $media = 'all', $queue = null)`
Maybe drop $ver parameter?

**Comment by tablatronix** [comment]
I can make it default so its optional

**Comment by dimayakovlev** [comment]
Thank you, Shawn. Embedded styles and scripts are very useful.

**Comment by tablatronix** [comment]
fixed

**Comment by tablatronix** [comment]
I think inline is the correct term actually.
