### ISSUE TITLE
Backend assets are registered in frontend too

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1169]
So they can be queueing in frontend. It's not good.

**Comment by dimayakovlev** [comment]
It's nice not include jquery or fontawesome with theme, and use `queue_script('jquery', GSFRONT);`, but their paths includes name of admin folder. So everybody knows it.

**Comment by tablatronix** [comment]
Yeah but until we have a way to share assets and move them outside of admin, its really a convenience only. There is CDN only support, but i added cdn fallback, i can make that optional also.

I just added the ability to disable cdnfallback ( which reveals gsdmin )

Options around this are

* GSNOCDN false
* GSCDNFALLBACK false

This will allow jquery,jquery-ui,and fontawesome to be queued on front end and hide all references to gsadmin/

Another option is to modify the ASSETURL and use a blind rewrite to hide /gasadmin foldername

**Comment by tablatronix** [comment]
not gonna disallow front end registration atm
But added some capability to help shield admin suggestions welcome.

Only solution is to move assets into pubic space.
