### ISSUE TITLE
changedata-save and changedata-save-draft hooks

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1172]
Will have to maintain two hooks for saving custom fields data and etc. Maybe use one hook?

**Comment by tablatronix** [comment]
How about three hooks? Also for actual saving a fikter should be used anyway

**Comment by dimayakovlev** [comment]
I like idea about three hooks.

**Comment by tablatronix** [comment]
executing `changedata-save` valid for published and draft
added individual hooks for each `changedata-save-published` and `changedata-save-draft`

**Comment by tablatronix** [comment]
fitlers are new in 3.4 so legacy support is not necessary.
