### ISSUE TITLE
3.4 Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by webketje** [GetSimpleCMS/GetSimpleCMS#1175]
When: when navigating to `admin/install.php` on first install
In: [..]\admin\inc\template_functions.php on line 2078.
PHP version: 5.4
Reference: [SO answer](http://stackoverflow.com/questions/1532693/weird-php-error-cant-use-function-return-value-in-write-context#answer-2173318)
Fix: don't call `empty` on anything else than variables if support for PHP 5.5- is required.
Sample implementation:
````
function getCollectionItemSlug($slug,$default = null){
	$temp = trim($slug);
	if ($slug == null or empty($temp)){
	  $temp = trim($title);
		if ($title != null && !empty($temp)) {
			$slug = $title;
		}
	}	
	$slug = trim(prepareSlug($slug));
	if(empty($slug)) return; // errormode return null
	return $slug;
}
````

**Comment by tablatronix** [comment]
Do you get any of these in stable ?

**Comment by tablatronix** [comment]
Looks like i need a new wamp, easyphp now charges for modules, ughhh
Ill find a 5.4 version and check on this, makes sense this is a common issue with those versions.

**Comment by tablatronix** [comment]
Can you test this, I do not have anything below 5.5 atm

**Comment by webketje** [comment]
DW, just tested on 5.4, no errors.
