### ISSUE TITLE
codemirror init error when JQUERYUI tabs are selected

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1180]
Codemirror instances inside a jqueryui tab are only initialized properly if they are visible, when switching tabs, codemirror must first be focused to init.

Possible solution
use codemirror `refresh` and or detect jui `activate`

codemirror/CodeMirror#71

- [ ] add handler to framework

**Comment by dimayakovlev** [comment]
Good if this can be resolved in GS core.
