### ISSUE TITLE
Call save_codeeditors() on editform submit

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1187]
Shawn, since you fix https://github.com/GetSimpleCMS/GetSimpleCMS/issues/1180, can you add this into core js:
```
$('#editform').on('submit',function(e){
  save_codeeditors();
});
```

**Comment by tablatronix** [comment]
Is this even necessary ? codemirror usually updates textareas itself fairly well.

**Comment by tablatronix** [comment]
I guess i still need to do it for replacement editors

**Comment by dimayakovlev** [comment]
Thank you!
