### ISSUE TITLE
Hiding css/js files in GS theme editor

### ISSUE THREAD

**Issue by konsthur** [GetSimpleCMS/GetSimpleCMS#1205]
It'd be nice to prevent editing some files directly from GS theme editor

**Comment by webketje** [comment]
@konsthur you might be interested in [gs_usermgr](https://github.com/webketje/gs_usermgr) (not in GS Extend yet).
This can perfectly be done if you give the users a user group for which the permission is denied, eg with the following plugin:
````
<?php // register plugin
register_plugin(
    'site-perms',
    'Site permissions',
    '1',
    null,
    null,
    'Site permissions',
    'settings',
    null
);

add_action('permissions-hook', 'my_permissions');

function my_permissions() {
  $usermgr = usermgr();
  $usermgr->register('permissions', 'access_js_css_files');

  if (myself(false) === 'theme-edit.php') {
      add_filter('permissions-css', function($style) {
          $current_user = current_user();
          if ($current_user->cannot('access_js_css_files'))
            $style .= '#theme_files option[value$=".css"], #theme_files option[value$=".js"] { display: none; }';
          return $style;
      });
  }
}
````
See the [wiki](https://github.com/webketje/gs_usermgr/wiki) for more info.

**Comment by konsthur** [comment]
@webketje I'll check it, thank's for posting.

**Comment by tablatronix** [comment]
f539a4191492a52db77f053875175d0a37c34548
oops put wrong issue number

**Comment by tablatronix** [comment]
#719

**Comment by webketje** [comment]
Great, this is much better than the CSS hiding.
