### ISSUE TITLE
GS 3.4 - Cleaner dropzone design

### ISSUE THREAD

**Issue by webketje** [GetSimpleCMS/GetSimpleCMS#1210]
Can we have a cleaner dropzone design for GS 3.4? 
Compare current vs proposal:
![](https://i.imgur.com/GclEJsX.png) ![](https://i.imgur.com/66UWfa7.png)

Changes: opacity: 0.3 -> 0.5, font-size: 16 -> 14px, border 3 -> 1px, adjusted margin;
Font-awesome icon size: 1em

**Comment by tablatronix** [comment]
I guess

**Comment by tablatronix** [comment]
I made it a bit cleaner, somewhere between the two

**Comment by tablatronix** [comment]
hell next version will have full page drop and browser to browser and editor drop probably

**Comment by tablatronix** [comment]
acceptable ?
