### ISSUE TITLE
DEV: Clean install - directory permissions errors

### ISSUE THREAD

**Issue by hameau** [GetSimpleCMS/GetSimpleCMS#1220]
A clean install has 'Not writable' errors on ```data/other/logs``` and ```backups/users```; both have perms of 0705.

GSCHMOD is not set in gsconfig.php.

In fact, these are writable as the webserver and php run as the (OVH account) user. GS works and files can be written to the two directories.

Attached is the debug console contents after install.php has run (install-php_debug.txt
[install-php_debug.txt](https://github.com/GetSimpleCMS/GetSimpleCMS/files/819239/install-php_debug.txt)
).

GS3.4 master, 2017/03/05; clean install on ovh.com shared hosting. OVH perms recommendations are 0705 or 755 (directories) and 0604 or 0644 (files). PHP files with 0777 will give 500 Server Error.

**Comment by hameau** [comment]
To add some perspective, directory permissions on this hosting have usually required manual adjustment, but recent versions of GS include more of the default directories in the distributed .zip.

Perhaps it's simply a matter of adding the ```data/other/logs``` and ```backups/users``` empty directories to the .zip. Is there a downside?

(It's a long time since I did a completely clean install in a bare directory - the issue doesn't arise with updating an existing install.)

**Comment by tablatronix** [comment]
are they actually not writable ?

health check just checks against GSCHMODDIR, set your GSCHMODDIR to your 0705 then if that is what your host uses.

**Comment by tablatronix** [comment]
@hameau  ?

**Comment by hameau** [comment]
(Sorry, I wrote a reply and could have sworn I pressed 'Comment' ...)

Yes, they are writable.

I didn't know about the new definitions. If I set 'GSCHMODDIR', 0705 in gsconfig.php, there is no error.

Newly created (by GS) directories should be 0755 with default GS settings, I think? OVH sets a default PHP umask of 0072. There is no problem with php chmod(), which can be used to set 0755 on a directory that already exists and umask can also be changed with php.

Is it reasonable for GS to run umask(0022)? I can understand if you don't want to add that to core code, so is there a way to have umask() run ahead of GS code (hook to a file?) ?

Should GS be using GSCHMODDIR for mkdir() and chmod(), as well as for the health check (and GSCHMODFILE for files)?

**Comment by tablatronix** [comment]
what do you mean "should" it already does.

**Comment by tablatronix** [comment]
Maybe health check can be smarter ? Can it check actual perms, or do a write test? Probably not worth implementing.

**Comment by tablatronix** [comment]
it looks like i have a bug in iswritable..

```
function checkWritable($path,$perms = null){
	$writeOctal = getChmodValue($path);
	if(!isset($perms)) $perms = check_perms($path);
	// debugLog(__FUNCTION__ . ' ' . $path . ' ' . $perms .' > '. decoct($writeOctal));
	$iswritable = is_writable($path);
	$iswritable = $perms >= decoct($writeOctal);
	return $iswritable;
}
```
I am ignoring php is_writable return..

**Comment by hameau** [comment]
> what do you mean "should" it already does.

If you mean for this:
> Should GS be using GSCHMODDIR for mkdir() and chmod() ...

There are still some GSCHMOD being used, e.g., in update.php, upload.php.

GSCHMODDIR and GSCHMODFILE will need to be included in temp.gsconfig.php (instead of GSCHMOD for new installs?).

> I am ignoring php is_writable return

I was trying to work out how you were using it. ;-)

**Comment by tablatronix** [comment]
Yeah i guess i inteded it to fallback to perms check ,or OR the results, ill have to test and see what i intended that func to do.

**Comment by tablatronix** [comment]
Actually all calls need to be changed to use `getChmodValue()` so it handles legacy CHMOD and CHMODFILE

**Comment by hameau** [comment]
> umask is something I really do not want to touch in GS ...

That is a reasonable POV, though your quote was written five years ago and may not be applicable a) nowadays and b) in a modern shared hosting env with proper separation.

Anyway, 0755/0644 should be safe everywhere and if is_writable() works ;-), nothing more should be necessary.

**Comment by tablatronix** [comment]
I think this is resolved
