### ISSUE TITLE
php 7 deprecates char arrays

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1223]
http://get-simple.info/forums/showthread.php?tid=9557&pid=59826#pid59826

`$menu_extract[] = "";`

**Comment by cnb** [comment]
So it should be `$menu_extract = array();` ?

**Comment by tablatronix** [comment]
no it should be string concatenation

**Comment by tablatronix** [comment]
hmm looks like this function actually returns mixed string and arrays.
ugh

**Comment by cnb** [comment]
I think that `$menu_extract` is an array, so it should be initialized with `= array()` (as I said). That was the problem.

So, 9315fe84591510bf2041c56d69de26863f1d901c should be reverted (the problem was not there).

**Comment by tablatronix** [comment]
But it is defined as a string
$menu_extract = '';

I really didnt know what to do here, its possible if was getting type juggled before.

**Comment by tablatronix** [comment]
Ok so yeah it should be array if not xml string arg.
This is really bad practice, ill fix it though

**Comment by cnb** [comment]
Yes, $xml is a bool parameter but then reused as string to be returned...

**Comment by tablatronix** [comment]
I fixed this in june, and never pushed it....

**Comment by cnb** [comment]
:-?
I saw it was for 3.3.14...
