### ISSUE TITLE
CVE 2017-8081

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1224]
generate_salt unnecessarily weak.

- [ ] mt_rand weak
- [ ] sub str sha1 to 22 characters ( why )?

we allow custom salt and it has no problems being longer than 22 chars so i have no idea where this restriction came from. Do not see any breakage from removing it.

refs
#880 
#931

**Comment by WilliamParks** [comment]
There are a couple options from what I've seen, but they aren't as drag & drop as I'd hoped. 
- openssl_random_pseudo_bytes() works, but it only is available in php5.3 onward, per [https://secure.php.net/manual/en/function.openssl-random-pseudo-bytes.php](https://secure.php.net/manual/en/function.openssl-random-pseudo-bytes.php), while the listed requirements for the CMS are 5.2+

- Userland implementation. The PHP website lists a recommended project in the note on [https://secure.php.net/manual/en/function.random-int.php](https://secure.php.net/manual/en/function.random-int.php), but that requires including an additional project, making sure the license works, etc.

Thoughts?

**Comment by WilliamParks** [comment]
An alternative would be to branch on version, with 5.3+ getting the secure version, and 5.2 staying as is (idk how many users use the hotfix, but are on php v5.2).

**Comment by tablatronix** [comment]
wrap a more secure option in a 5.2 fallback

**Comment by tablatronix** [comment]
pr #1226

**Comment by tablatronix** [comment]
- [ ] test speed in windows php 5.6, add windows exclusion if necessary.

**Comment by cnb** [comment]
Perhaps it would be better using `function_exists('openssl_random_pseudo_byte')` with fallback as you commented, see here:
http://get-simple.info/forums/showthread.php?tid=10305&pid=61808#pid61808

**Comment by tablatronix** [comment]
I already commited, but the site went 502 again so i cant post

**Comment by tablatronix** [comment]
- [x] add function exists check was missing in PR, some installs do not have opensll funcs
