### ISSUE TITLE
Reset any user's password through admin/resetpassword.php

### ISSUE THREAD

**Issue by Xyntax** [GetSimpleCMS/GetSimpleCMS#1227]
* Version 3.3.13

This page can reset any user's password to a 6-bit random value, maybe it needs a `login_cookie_check();` ?

**Comment by tablatronix** [comment]
Yeah it is an anonymous reset, it would not work any other way, i guess it could be enhanced with a known input like require email not password or some other secret. It also is a denial of service capable.

**Comment by tablatronix** [comment]
added hooks in 3.4 for plugins to add advanced stuff
