### ISSUE TITLE
login hooks

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1235]
Add login hooks similar to resetpass hooks i just added.
#1233

**Comment by tablatronix** [comment]
```
exec_action('load-login');
exec_action('login-main'); // @hook login-main before passwword reset main html output
exec_action('login-extras'); // @hook login-extras

exec_filter('login',true); // @filter resetpw filter bool allow
```

**Comment by tablatronix** [comment]
#719

**Comment by beejay41** [comment]
I'm having problems using the login filter.
Firstly, returning FALSE in the plugin filter function does not appear to be returned by exec_filter().
Secondly, any login filter needs information about the user, at least $USR, but better $data.

If the filter is called as follows, the plugin will have the user's details and can return the outcome of any checks:
```
	# do the username and password match?
	$allow = TRUE;
	exec_filter('login',[$data,&$allow]); // @filter login filter bool allow

```

**Comment by beejay41** [comment]
Thanks, Shawn, I'd have never spotted that.
Login hook working as expected.

**Comment by tablatronix** [comment]
Yeah I have been using typed languages lately, I forgot php is loose sometimes.
