### ISSUE TITLE
Filename cleaning doesn't include file extension

### ISSUE THREAD

**Issue by hameau** [GetSimpleCMS/GetSimpleCMS#1236]
With GSUPLOADSLC undefined, or defined as true, uploaded files only have the file name cleaned and changed to lowercase, leaving the extension unchanged.

In both ```upload.php``` and ```upload-uploadify.php``` the filename is split into name and extension and only the name part goes through clean_img_name().

E.g., uploaded file 'IMG_1000.JPG' is saved as 'img_1000.JPG'.
and there is no cleaning of the extension:
E.g., uploaded file ```Upload-<br>-file.<p>txt<br>``` is saved as ```Upload-file.<p>txt<br>```.

See also GS forums:
http://get-simple.info/forums/showthread.php?tid=2766&pid=61019#pid61019
http://get-simple.info/forums/showthread.php?tid=9973

**Comment by tablatronix** [comment]
Not hotfixed yet

**Comment by cnb** [comment]
function `getFileName` has the same description as `getFileExtension` (749ff21d5fa544031f339f59293adcb1895dafd6)
