### ISSUE TITLE
debug_backtrace() was changed in PHP 7

### ISSUE THREAD

**Issue by bigin** [GetSimpleCMS/GetSimpleCMS#1238]
Strange behavior of `debug_backtrace()` detected, seems that it was changed in `PHP 7 >`, so that `add_action()` will not work in the same way. The counter `$shift` is now one level less. An example to reproduce it:

```php
<?php

register_plugin(
    'add_action_test',
    'add_action_test',
    '0.1',
    'J. Ehret',
    'http://ehret-studio.com',
    'Testing strange behavior of add_action()',
    '',
    ''
);

add_action('index-post-dataindex', 'add_action_test');

function add_action_test() {
    include __DIR__.'/A.php';
    $a = new A;
    $a->fireFoo();
}
```

A.php looks as follows:
```php
<?php

class A {
    function fireFoo() {
        add_action('theme-header', function() { echo 'here in foo() ...'; });
    }
}
```

Adding `version_compare()` into `add_action()` could solve that issue:

```php
...
$shift=count($bt) - 4;
if(version_compare(PHP_VERSION, '7.0.0', '>=')) {
    $shift--;
}
...
```

**Comment by tablatronix** [comment]
Thanks

**Comment by tablatronix** [comment]
Is this in stable or 3.4 ?

**Comment by tablatronix** [comment]
nm, I found the change
php7 debug_backtrace no longer includes
`call_user_func` and `call_user_func_array` as calls

**Comment by tablatronix** [comment]
It appears this only applies to some instances or only 7.1 maybe ?

**Comment by bigin** [comment]
What's the exact error message, do you have an example? 
Tested with PHP 7.1.8 runs without any problems

**Comment by tablatronix** [comment]
http://get-simple.info/forums/showthread.php?tid=10579&page=2

complete failure of front end

**Comment by tablatronix** [comment]
I bet its 7.1 only and they regressed it in 7.2, although I find no official notes on this change in php, only that variables change to refs inside bt

**Comment by tablatronix** [comment]
This was not supposed to be in 3.3.14, I accidentally added it

**Comment by bigin** [comment]
Confirm, the decrement of `$shift` causes a failure in the frontend. Strange, but the problem described above is solved with this ... Could it be that there is something wrong with the add_action?

**Comment by tablatronix** [comment]
I will probably have to crawl the backtrace to get the level to get proper callee, especially if adding hooks inside hooks, either way we should not be using backtrace at all if we can avoid it.

**Comment by bigin** [comment]
I did some testing, here's what I was able to find out. It looks as this if-statement is the problem:
`if ((isset ($live_plugins[$pathName.'.php']) && $live_plugins[$pathName.'.php']=='true') || $shift<0 )`

... especially `$live_plugins[$pathName.'.php']=='true'` because it's indexing a wrong file `A.php` as a plugin and returns `false`.

what's this part for ` || $shift<0 ` ?

**Comment by tablatronix** [comment]
I do not recall, probably in case it was never found in backtrace, either way this is no longer used in 3.4 I rewrote the whole thing. I would just not use nested hooks, I mean there is not really a reason you could not avoid it.

**Comment by tablatronix** [comment]
Not sure where this left off, I think it can be ignored.

**Comment by tablatronix** [comment]
adds GSBTFIX optional

DEFINE GSBTFIX true // Backtrace FIX for some versions of php 7
