### ISSUE TITLE
longer meta description

### ISSUE THREAD

**Issue by cnb** [GetSimpleCMS/GetSimpleCMS#1240]
It seems that google is now accepting longer descriptions, up to 320 chars (instead of 160 or so)
https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596

Character count:
- GS 3.3.x has it hardcoded in jquery.getsimple.js
```
var remaining = 155 - jQuery('#post-metad').val().length;
```
- GS 3.4, in edit.php:
```
<textarea class="text short charlimit" data-maxLength='155' id="post-metad" ...
```

There's also (both GS 3.3.x and 3.4) the generated meta description (if GSAUTOMETAD enabled):
- In `get_page_meta_desc` (theme_functions.php)
```
$desc = getExcerpt($desc,160); // grab 160 chars
```

Perhaps it would be convenient to have a gsconfig setting for this (that defaults to 320)

**Comment by tablatronix** [comment]
Good to know, i thought this was a W3c thing.

**Comment by cnb** [comment]
not for 3.3.14 too?

**Comment by tablatronix** [comment]
you think this warrants a hotfix ?

**Comment by tablatronix** [comment]
I do not know if increasing the default is warranted at this point, I mean it seems this was gleamed from stats and not a google recommendation, or any others that I have seen.

**Comment by cnb** [comment]
https://www.seroundtable.com/google-longer-meta-descriptions-24912.html

I think that at least this should be changed for the "x characters remaining", so that users see they can type longer descriptions. As for the auto metad, I don't care much as it is disabled by default (#591)

I said 3.3.14 because I saw there's a milestone for that version.

**Comment by tablatronix** [comment]
Yeah you can only pick one milestone, I might add a hotfix label , it would be useful going forward.
I already fixed this in 3.4, so let me know if that works for you. as far as the default, I will be taking suggestions on all defaults during alpha feedback.

**Comment by cnb** [comment]
I've had to replace `$content` by `getPageGlobal('content')`  in  `get_page_meta_desc` (theme-functions.php line 114).

After that, it seems to work okay.

**Comment by tablatronix** [comment]
good catch, I think i wound up doing some cleanup of alot of stuff inadvertently in another branch, i will have to figure out how to merge that in at some point.
