### ISSUE TITLE
codemirror theme selection

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1241]
Which themes should be included
All themes are provided and enabled in 3.4 alpha or test here
https://codemirror.net/demo/theme.html

- [ ] 3024-day.css
- [ ] 3024-night.css
- [ ] abcdef.css
- [ ] ambiance-mobile.css
- [x] ambiance.css
- [ ] base16-dark.css
- [ ] base16-light.css
- [ ] bespin.css
- [ ] blackboard.css
- [ ] cobalt.css
- [ ] colorforth.css
- [x] default.css
- [x] dracula.css
- [ ] duotone-dark.css
- [ ] duotone-light.css
- [x] eclipse.css
- [ ] elegant.css
- [ ] erlang-dark.css
- [ ] hopscotch.css
- [ ] icecoder.css
- [ ] isotope.css
- [ ] lesser-dark.css
- [ ] liquibyte.css
- [x] material.css
- [x] mbo.css
- [ ] mdn-like.css
- [ ] midnight.css
- [x] monokai.css
- [x] neat.css
- [x] neo.css
- [ ] night.css
- [x] panda-syntax.css
- [x] paraiso-dark.css
- [x] paraiso-light.css
- [ ] pastel-on-dark.css
- [x] railscasts.css
- [ ] rubyblue.css
- [ ] seti.css
- [x] solarized.css
- [ ] the-matrix.css
- [ ] tomorrow-night-bright.css
- [ ] tomorrow-night-eighties.css
- [ ] ttcn.css
- [ ] twilight.css
- [ ] vibrant-ink.css
- [ ] xq-dark.css
- [ ] xq-light.css
- [ ] yeti.css
- [ ] zenburn.css

**Comment by tablatronix** [comment]
#1222

**Comment by cnb** [comment]
I prefer light ones like eclipse.css and neat.css, though I suppose I'd have to check how they look in GS.
Do you intend to include many of them?

Would it be possible (e.g. by a custom admin plugin) to include others?

**Comment by tablatronix** [comment]
Yes they are selected via a gsconfig, but there are a ton, I added them all for now. Some make no sense to me

**Comment by tablatronix** [comment]
Ah looks like some of the backgrounds are not working that is why they look wrong. Ill have to investigate and compare to codemirror site

**Comment by ThomasHelzle** [comment]
I can live with the default, although normally I'm more into dark ones, but in the context of the light GS admin theme those can feel a bit strenuous to the eye. I'd probably use something like base 16 dark or blackboard or do my own, like I did for Komodo Edit (shades of orange on dark grey).
Overall not something that bothers me too much - larger edits I do outside of GS anyway.

**Comment by datiswous** [comment]
imo (+=good, -=bad, not listed=I don't care):
default +
abcdef +
blackboard +
cobalt -
erlang-dark -
hopscotch -
icecoder +
isotope +
vibrant-ink +
zenburn -
yeti -
xq-light -
solarized dark -

**Comment by tablatronix** [comment]
fc404d1bd49ba8f1c67034eca1d3167b38b28d08
