### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by alex-phillips** [GetSimpleCMS/GetSimpleCMS#1245]
You guys need to update requirements for installation as well as your 'site health check' page in the admin interface. Currently it says php 7+ is supported / working but I have found several cases where that is not the case. Also, the current version does not work with Apache. The .htaccess file includes directives that haven deprecated and/or replaced with new syntax. Specifically `Deny from...` and `Order allow,deny`.

**Comment by tablatronix** [comment]
Where does it say that?
