### ISSUE TITLE
constants in temp.gsconfig.php not read during installation

### ISSUE THREAD

**Issue by backit** [GetSimpleCMS/GetSimpleCMS#1254]
I use latest stable version: 3.3.13
I write a script to automate installation. I set, before install the website, in temp.gsconfig.php, GSLOGINSALT and GSUSECUSTOMSALT but after finish installation i cannot login to new website because the password is saved without salt only with sha1. Solution is to copy temp.gsconfig.php to gsconfig.php before run the installation, but as defined in admin/setup.php at line 17:
if(defined('GSLOGINSALT')) { $logsalt = GSLOGINSALT;} else { $logsalt = null; }
GSLOGINSALT should be used.
Best regards

**Comment by tablatronix** [comment]
so whats the problem ?

**Comment by backit** [comment]
In setup.php gsloginsalt is ignored if defined in temp.gsconfig. 
if i understood the code, setup.php call inc/common.php that include gsconfig that It doesn't exist because It is not yet copied from temp.gsconfig . So where It is expected that setup.php should find gsloginsalt?

**Comment by tablatronix** [comment]
In gsconfig.php

**Comment by backit** [comment]
Exactly, but it does not exist yet. Maybe temp.gsconfig.php should be copied in gsconfig.php before run setup.php?

**Comment by backit** [comment]
Give it a try easy to better understand what i'm trying to explain, unzip the downloaded getsimple zip file change gsloginsalt in temp.gsconfig.php and run install. When finished you wont be able to login

**Comment by tablatronix** [comment]
You have to make your own gsconfig if you want a custom install. Do not use the temp file thats why its called temp.

**Comment by backit** [comment]
I saw, but in setup.php there is:
if(defined('GSLOGINSALT')) { $logsalt = GSLOGINSALT;} else { $logsalt = null; }
GSLOGINSALT should be used.
Defined in gsconfig.php that does not exist, so where define gsloginsalt for setup.php?

**Comment by tablatronix** [comment]
You have to do it yourself, its a custom thing, obviously you want to customize setup, so you have to create your own gsconfig.
