### ISSUE TITLE
3.4 upload issues

### ISSUE THREAD

**Issue by n00dles** [GetSimpleCMS/GetSimpleCMS#1258]
Just checking the 3.4 release. 

couple of issues on the upload.php page. I couln't find any GH issues on these so close if already dealt with. 

- [x] drag/drop not working for the dropzone. 
- [x] when you upload using the clickable menu item. on upload it refreshes to a list of files without the handy thumbnails. clicking files in the top menu returns to the default list. 
- [x] lightbox does not work after upload

**Comment by n00dles** [comment]
Ah ok, very confusing that image that says "Drop images here" which you would expect to be able to drop your images on. and not the link above it..... 

would be better to have the main div on the left hand side droppable ??

**Comment by tablatronix** [comment]
Thats not normal, I recently had to fix some stuff with that , ill look tomorrow and fix it

**Comment by tablatronix** [comment]
Can you create prs? If you dont mind, I am working on some major git sync and cherry picking.

**Comment by tablatronix** [comment]
What os browser?

**Comment by tablatronix** [comment]
Dropping in dotted drop zone works for me
osx chrome, safari

**Comment by tablatronix** [comment]
c73366d4dcece01664fc655a87714010f208a049

**Comment by tablatronix** [comment]
These are most event bind lost issues

**Comment by tablatronix** [comment]
ok so this commit will do the following for now ( we will probably change the file list to just toggle showthumbs on and off eventually )

as of now, if showthumbs is not on, and filter is image, then on upload the filter will change to all and showthumbs will be forced on for that page session. This way you still see thumbnails, and you will see other files that save. We can add an additional upload check for images flag and restrict this behavior to only activate if a non image is actually uploaded.

**Comment by tablatronix** [comment]
Are you still having issues with drop zone?
I see no problem.

**Comment by n00dles** [comment]
All seems to be working fine again now. This can be closed.
