### ISSUE TITLE
Add extra clean URL - ".htaccess" 

### ISSUE THREAD

**Issue by emresaracoglu** [GetSimpleCMS/GetSimpleCMS#1261]
Hello there,
I created a page and the page contains many pages with the [switch](http://php.net/manual/en/control-structures.switch.php) but the URL does not look ugly.*

> https://helloWorld.com/page?cmd=content&cID=500&tID=3

to 

> https://helloWorld.com/page/content/500/3

How do I change the URL?

**Comment by tablatronix** [comment]
Settings fancy url
Read the wiki use the forum

**Comment by tablatronix** [comment]
Oh if it still not working then there is a problem with your htaccess rewrite
