### ISSUE TITLE
PHP 7.1+ menu_data() fatal error

### ISSUE THREAD

**Issue by skylarmt** [GetSimpleCMS/GetSimpleCMS#1269]
After upgrading my server from PHP 7.0 to 7.2, I got a fatal error in `theme_functions.php` on line 475 (`$menu_extract[] = $specific;`).  It was caused by `$menu_extract` being a string, not an array:

    function menu_data($id = null,$xml=false) {
        $menu_extract = '';

When I changed it to this:

    function menu_data($id = null,$xml=false) {
        $menu_extract = [];

my site came back.

From [this document on php.net](http://php.net/manual/en/migration71.incompatible.php) regarding breaking changes in PHP 7.1:
> **The empty index operator is not supported for strings anymore**
> Applying the empty index operator to a string (e.g. $str[] = $x) throws a fatal error instead of converting silently to array.

**Comment by tablatronix** [comment]
dup #1223
