### ISSUE TITLE
Missing file - Warning

### ISSUE THREAD

**Issue by emresaracoglu** [GetSimpleCMS/GetSimpleCMS#1282]
Hello,

I can't create a new page, and I can't edit it on the current page. I'm getting this screen on the site health page.

name|status
-- | --
/data/ | Good 'Deny' file - OK
/data/uploads/ | Good 'Allow' file - OK
/data/users/ | Missing file - Warning
/data/cache/ | Missing file - Warning
/data/thumbs/ | Good 'Allow' file - OK
/data/pages/ | Missing file - Warning
/plugins/ | Good 'Deny' file - OK
/data/other/ | Missing file - Warning
/data/other/logs/ | Missing file - Warning
/theme/ | No file - OK

What could be the reason for this?
Thank you.

_Version: 3.3.13 ob nginx_

**Comment by tablatronix** [comment]
If you get a 404 its your host mod sec security blocking you

**Comment by emresaracoglu** [comment]
No, I'm not getting any 404. I can access pages but I get this error if I want to edit the page content: `Error: edit.`

![](https://user-images.githubusercontent.com/297968/42003784-bb5d5580-7a75-11e8-9d40-4d9c5caa1797.png)

**Comment by tablatronix** [comment]
Hmm check debug log? Use forums for support

**Comment by emresaracoglu** [comment]
I updated the system files with the new version. Currently working without problems.
**Thank you for your time!**
