### ISSUE TITLE
Cross Site Scripting Vulnerability in Latest Release 3.4.0.9

### ISSUE THREAD

**Issue by liao10086** [GetSimpleCMS/GetSimpleCMS#1284]
Hi, I would like to report Cross Site Scripting vulnerability in latest release.

Description:
Cross-site scripting (XSS) vulnerability in edit.php

Steps To Reproduce:
1.create new page
url: http://localhost/admin/edit.php
title input payload `<img src=1 onerror=alert(document.cookie)>`
![5](https://user-images.githubusercontent.com/37523122/42611939-1d433700-85cb-11e8-953c-5938b51bf352.jpg)
2、clike the link
![6](https://user-images.githubusercontent.com/37523122/42612000-64689256-85cb-11e8-9b27-dd1e3907f07c.jpg)
3、xss cookie
![3](https://user-images.githubusercontent.com/37523122/42612015-7f02435a-85cb-11e8-8603-3cbe683af081.jpg)
![4](https://user-images.githubusercontent.com/37523122/42612020-84538684-85cb-11e8-9538-0a78ff03f42a.jpg)

Release Info:
3.4.0.9

author by xijun.liao@dbappsecurity.com.cn

**Comment by tablatronix** [comment]
- [ ] unsanitized theme output of title
- [ ] unsanitized title input, persistent

**Comment by tablatronix** [comment]
#1068

**Comment by tablatronix** [comment]
#1293 
fix in hotfixes

**Comment by tablatronix** [comment]
#1306

**Comment by tablatronix** [comment]
- [ ] fix in dev
