### ISSUE TITLE
Null is not a valid callback

### ISSUE THREAD

**Issue by bigin** [GetSimpleCMS/GetSimpleCMS#1285]
`sortCustomIndexCallback()` function will throw a warning on current dev, because $prepare is a null not a valid callback.

**Comment by tablatronix** [comment]
what php version ?

**Comment by bigin** [comment]
7.1.8
Hmm, but I can't reproduce it now. Let me do a little more testing.

**Comment by bigin** [comment]
Weirdly, I can't reproduce it now, maybe it was my mistake. But it is probably better to define $prepare as an empty string instead of null.
