### ISSUE TITLE
image manipulation warning

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1289]
`[14-Jul-2018 08:46:03 America/Chicago] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ImageManipulation has a deprecated constructor in /Users/user/projects/web/dev/getsimple/develop/admin/inc/imagemanipulation.php on line 17`

**Comment by tablatronix** [comment]
can you PR this?

**Comment by tablatronix** [comment]
Is this backward compatible ?

**Comment by cnb** [comment]
Yes. PHP >= 5
