### ISSUE TITLE
Call to undefined function exec_action()

### ISSUE THREAD

**Issue by emresaracoglu** [GetSimpleCMS/GetSimpleCMS#1299]
Hello,

I getting this error:

> PHP Fatal error: Uncaught Error: Call to undefined function exec_action() index.php line 47

PHP 7.1.10
What cloud be the reason? 
Thank you

**Comment by tablatronix** [comment]
version?

**Comment by emresaracoglu** [comment]
Hi,

The possible problem is with my files. I have replaced the existing files with the new files and solved.
Thanks
