### ISSUE TITLE
External Control of File Name or Path in 3.1.15

### ISSUE THREAD

**Issue by ziizhuwy** [GetSimpleCMS/GetSimpleCMS#1304]
The vulnerability exists in the "admin/log.php" parameter，it allows user delete anything he wants to delete.
Let me delete readme.txt
![image](https://user-images.githubusercontent.com/43847458/53943902-1b443500-40f9-11e9-85e0-1974ae3f3009.png)

1. open the URL:http://localhost:8000/GetSimpleCMS/admin/log.php?log=../../../readme.txt
![image](https://user-images.githubusercontent.com/43847458/53943928-2eef9b80-40f9-11e9-8541-2caa2d2ce5a3.png)
2.click "CLEAR THIS LOG",Log ../../../readme.txt has been cleared
![image](https://user-images.githubusercontent.com/43847458/53943966-50508780-40f9-11e9-945c-c641147e778c.png)
![image](https://user-images.githubusercontent.com/43847458/53943995-62322a80-40f9-11e9-9d1b-e279fc5e5efa.png)

**Comment by cnb** [comment]
Isn't this the same as #1303 ?
BTW 3.1.15 does not exist - I assume you mean 3.3.15

**Comment by ziizhuwy** [comment]
I'm so sorry,I don't see it before

Shawn A <notifications@github.com> 于 2019年3月8日周五 上午12:30写道：
