### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by RicPlan** [GetSimpleCMS/GetSimpleCMS#1324]

**Comment by codecobber** [comment]
Very much so. There are several developers who regularly update the source and release new versions. Not too sure when the next update is due though. Check out the GetSimple forum on the main website.

**Comment by RicPlan** [comment]
Okay, that's good news.
I love this CMS.

**Comment by tablatronix** [comment]
lol, check out 3.4 unreleased
