### ISSUE TITLE
Undefined index: HTTP_X_FORWARDED_HOST in:

### ISSUE THREAD

**Issue by craigs-stuff** [GetSimpleCMS/GetSimpleCMS#1328]
Came across this today. Undefined index: HTTP_X_FORWARDED_HOST in: admin/inc/basic.php LINES 823 and 827.

A possible solution as far as I can see is to use the getenv() method replacing:

`htmlentities($_SERVER['HTTP_X_FORWARDED_HOST'])` 

with 

`getenv(HTTP_X_FORWARDED_HOST)`

**Comment by tablatronix** [comment]
It just needs an isset check

**Comment by craigs-stuff** [comment]
I agree, just thought I'd raise the bug with you so it could be included in the next version of gs.

**Comment by tablatronix** [comment]
Getenv is for gs env not php

**Comment by craigs-stuff** [comment]
Thanks Shawn, maybe I've misunderstood. I read the php docs for getenv here: [https://www.php.net/manual/en/function.getenv.php]
I take it GS has it's own version then? I just used isset anyway to cover myself. I've only had the error come up once when yesterday in the office.

**Comment by tablatronix** [comment]
oh lol, sorry 

Yeah but this is a SERVER[] var, not sure if its global

**Comment by tablatronix** [comment]
I am not seeing this code..

**Comment by tablatronix** [comment]
What branch /version are you using ?

**Comment by codecobber** [comment]
GS version 3.3.1.5 the current version.

**Comment by tablatronix** [comment]
Hmm not seeing it in basic.php or anywhere mist be a plugin

**Comment by craigs-stuff** [comment]
You're right, I just installed a clean version of gs and cannot find that code anywhere. Kind of hoping that it's not related top the i18n plugins. . . will investigate further. Thanks again Shawn
