### ISSUE TITLE
Depreciated: Required parameter $x follows optional parameter $y

### ISSUE THREAD

**Issue by johnstray** [GetSimpleCMS/GetSimpleCMS#1343]
When declaring a function or a method, adding a required parameter after optional parameters is deprecated since PHP 8.0. If you have a require parameter (i.e. a parameter without a default value set in its signature) after an optional one (i.e. a parameter with a default value), it makes all parameters before it essentially required because the caller has to explicitly pass a value for optional parameters as well.

More information here: https://php.watch/versions/8.0/deprecate-required-param-after-optional

So far, I have seen this here... [ PHP 8.0.0, GS v3.4.0.9-alpha ]
- [ ] Required `$lang` follows optional `$plugin` - _/admin/inc/basic.php_ on line **1415**
- [ ] Required `$globali18n` follows optional `$plugin` - _/admin/inc/basic.php_ on line **1415**
- [ ] Required `$default` follows optional `$var` - _/admin/inc/basic.php_ on line **2504**

**Comment by tablatronix** [comment]
oh ffs php!
 lol

**Comment by webketje** [comment]
It is definitely best practice to put required params before optional ones, *but* with PHP8 also comes the ability to circumvent having to specify prior null args with [named arguments](https://stitcher.io/blog/php-8-named-arguments)

**Comment by tablatronix** [comment]
These shouldn't even exist, must have added new args to these at some point, Let me know if this breaks anything...
