### ISSUE TITLE
Add email template capability

### ISSUE THREAD

**Issue by n00dles** [GetSimpleCMS/GetSimpleCMS#343]
_Original author: tablatronics (July 23, 2012 14:39:50)_

Add functionality to email_template($message)

Allow user set templates.

Perhaps via a hook/global or theme template file.

email_template() is used in sendmail()
eg. password reset emails

_Original issue: http://code.google.com/p/get-simple-cms/issues/detail?id=343_

**Comment by tablatronix** [comment]
added filter `email_template`

**Comment by tablatronix** [comment]
#719
