### ISSUE TITLE
Separate settings and user profile pages

### ISSUE THREAD

**Issue by cnb** [GetSimpleCMS/GetSimpleCMS#408]
Now we have:
- settings.php
- settings.php#profile

No reason to have it this way, especially since there can be more than one user.

A new profile.php page maybe?

Not sure if this can have problems with some plugin, but I don't think so. There are separate hooks for each.

**Comment by tablatronix** [comment]
This does not work with multi user plugin, as the user bio and name always show up USR and not the editing userid. I might have to add alternate `extras` hooks to make this backward compatible with new and edit modes.

**Comment by tablatronix** [comment]
changed all the hooks
`profile-save`
`profile-added`
`profile-edited`
`profile-save`
`profile-extras`
`profile-extras-edit`
`profile-extras-add`
