### ISSUE TITLE
refactor components

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#624]
In order to implement a few features components have to be refactored.
- [x] Code highlight and Cke modularized so they can be used easily here
- [x] Component types (code,rich text) dependant on previous
- [x] Component active boolean
- [x] Theme functions getter by type, filter active, getraw

**Comment by tablatronix** [comment]
#739

**Comment by tablatronix** [comment]
- [ ] Component updates and deletions are performed on all components, this is unlikely to change in 3.4 but ideally a mod flag for changed or a delete flag will be passed along to form, so that not all components are re saved on every save.

Components update and deletions can be done in real time with ajax saves, or in batches but that will probably present an undo problem, someone could be doing many operations on several components at once and it would be hard to present undo functionality for this until we have diff undos, or we can backup components on a per component basis somehow.

- [ ] Deletions pose a problem because we show the component deleted but it wont actually be until the form is saved. Provide better ui handing of this.

**Comment by cnb** [comment]
Another possibility would be making the component management page work like page management: list of components, you edit one at a time.

**Comment by tablatronix** [comment]
Yeah I have that losted above but deferrer because it requires quite a bit of engineering and might as well be combined with theme components and related functionality.
