### ISSUE TITLE
Plugins refactor

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#679]
Refactor of plugins system.

#604 
#438 
#588 
#677 
#670 
#490 
#680

**Comment by tablatronix** [comment]
Test code make sure optimization is working for mutiple entries but one priority.

**Comment by tablatronix** [comment]
- [ ] I think filter cyclical calls are broken now

**Comment by dimayakovlev** [comment]
> I think filter cyclical calls are broken now

I think so too.

**Comment by tablatronix** [comment]
possibly fixed now
e01cf2ab0d4f724bbd68cba3f2b1bffbfbc7df98
