### ISSUE TITLE
Allow localized date formats

### ISSUE THREAD

**Issue by n00dles** [GetSimpleCMS/GetSimpleCMS#85]
_Original author: ccagle8 (November 03, 2010 03:40:31)_

http://get-simple.info/forum/topic/1103/strtotime-instead-of-strftime-function/

looks like we need to use iconv in basic.php where we output the date in both long and short format

_Original issue: http://code.google.com/p/get-simple-cms/issues/detail?id=85_

**Comment by tablatronix** [comment]
- [ ] since setlocale is not threadsafe perhaps we should see if this is possible without it, using conversions only.

**Comment by tablatronix** [comment]
format builder
http://strftime.net/

**Comment by tablatronix** [comment]
@cnb 
i set this up to set and restore locale only when doing dateformat(), do you see any problems with that?
I am pretty sure everyone does this in plugins and it works ok, although i am setting LC_ALL, not just LC_TIME, because LC_TIME has some known issues I was reading somewhere.

added helpers and globals to store NEWLOCALE and OLDLOCALE

**Comment by tablatronix** [comment]
e0ad236a67e4ac76c926cea1c54028e87dfc77bc

**Comment by tablatronix** [comment]
basename() is locale aware!

i am going to change to LC_TIME, and deal with issues as they arise.
I cannot find much besides this one comment on the php docs about having to set C_TYPE as well on some windows machines.

**Comment by tablatronix** [comment]
added `$category` params to locale helper methods

**Comment by cnb** [comment]
(Sorry for the delay)
You said:
> i set this up to set and restore locale only when doing dateformat(), do you see any problems with that?

No problem... As you say, plugins that use strftime (NM, I18N Search/etc., ...) do it that way,
