### ISSUE TITLE
prevent backend in frames x-frame policy

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#971]
`GSNOFRAME` != false

sets header x-frame deny

**Comment by tablatronix** [comment]
This is applied for front end also!

**Comment by cnb** [comment]
I suggest:
`true` or `1` (default) backend only
`false` or `0`  to disable
`'all'` (or `'always'` or `2`or whatever) both frontend and backend

**Comment by tablatronix** [comment]
yeah good ideas, since we could benefit from security on both, for contact
forms and front end user logins protection.

**Comment by tablatronix** [comment]
#1028

**Comment by tablatronix** [comment]
This has been shown to break ckeditor and i noticed it also breaks some custom filebrowsers.

default should be SAMEORIGIN to alleviate, but it will still cause issues for multiple ips, especially multiple bound ips in local enviroments, some plugins do not use SITEURL correctly and compute their own wrongly. namely i18n gallery.
